/* =========================================
   音樂幽浮 - 全站搜尋索引庫 (請勿手動編輯此檔案)
   ========================================= */

const siteSearchIndex = [
  {
    "type": "monthly",
    "name": "777",
    "artist": "YAO",
    "desc": "Chased the world<br><span class=\"zh-translate\">追逐世界</span><br>Let’s take the chosen squad and break into<br><span class=\"zh-translate\">帶上被選中的夥伴，一起闖入</span><br>未開拓領域<br><span class=\"zh-translate\">尚未開拓的領域</span><br>Don't be afraid Go all in<br><span class=\"zh-translate\">不要害怕 全力以赴吧</span>",
    "ytId": "OJoZX6W77qI",
    "date": "2026.08",
    "sourceTitle": "2026 8月",
    "coverImg": "img/monthly/2026/08.jpg",
    "url": "monthly.html#month-08"
  },
  {
    "type": "monthly",
    "name": "恋する神様",
    "artist": "Penthouse",
    "desc": "SOS恋する神様<br><span class=\"zh-translate\">SOS，戀愛之神啊</span><br>言いたい言えない破裂しそうだよ<br><span class=\"zh-translate\">想說卻說不出口，簡直快要爆炸了</span><br>止められないやめられない恋わずらい<br><span class=\"zh-translate\">這無法停止、也無法放棄的相思病</span>",
    "ytId": "md1_y2vqRJU",
    "date": "2026.08",
    "sourceTitle": "2026 8月",
    "coverImg": "img/monthly/2026/08.jpg",
    "url": "monthly.html#month-08"
  },
  {
    "type": "monthly",
    "name": "オリオン!",
    "artist": "YOASOBI × Overwatch",
    "desc": "夜空に寄り添い並ぶ あの星のように<br><span class=\"zh-translate\">在夜空中相依並列的 就像那兩顆星星一樣</span><br>きっときっと 本当は二人<br><span class=\"zh-translate\">一定、一定 其實我們兩個人</span><br>ずっとずっと 想い合っていたのに<br><span class=\"zh-translate\">一直、一直 明明始終都彼此思念著對方</span>",
    "ytId": "EjaQdBcF6K4",
    "date": "2026.08",
    "sourceTitle": "2026 8月",
    "coverImg": "img/monthly/2026/08.jpg",
    "url": "monthly.html#month-08"
  },
  {
    "type": "monthly",
    "name": "Bubble",
    "artist": "tuki.",
    "desc": "（*強烈建議大家都給我去聽原版的-`д´-）<br><br>弾ける恋ならそれでもいい<br><span class=\"zh-translate\">即使這是一段終將破裂的戀情，也沒關係</span><br>泡になるまで笑っていたい<br><span class=\"zh-translate\">在化作泡沫之前，我想一直笑著</span><br>君となら笑えるよって 君のこと諦めやしないから<br><span class=\"zh-translate\">因為只要和你在一起，我就能笑著面對一切，所以我絕對不會放棄你</span>",
    "ytId": "5ZdJlEYRTMw",
    "date": "2026.08",
    "sourceTitle": "2026 8月",
    "coverImg": "img/monthly/2026/08.jpg",
    "url": "monthly.html#month-08"
  },
  {
    "type": "monthly",
    "name": "残酷になりますように",
    "artist": "ユイカ",
    "desc": "（*這次ユイカ的新曲歌詞非常值得細細品味！）<br><br>貴方がいる世界で 宝くじが当たりますように<br><span class=\"zh-translate\">在有你存在的這個世界裡 希望你能幸運地中獎</span><br>貴方が観たがっていたアニメが 第10期くらい続きますように<br><span class=\"zh-translate\">希望你一直想看的那部動畫 能一路推出到第 10 季左右</span><br>幸せに過ごしてね、風邪に気をつけてね。<br><span class=\"zh-translate\">希望你能幸福地生活，也要小心別感冒了。</span>",
    "ytId": "Xs7DfpykDtw",
    "date": "2026.08",
    "sourceTitle": "2026 8月",
    "coverImg": "img/monthly/2026/08.jpg",
    "url": "monthly.html#month-08"
  },
  {
    "type": "monthly",
    "name": "GG EZ",
    "artist": "M.Sasuke",
    "desc": "Fucking EZ 負けたつもりはないけどね<br><span class=\"zh-translate\">簡單得不得了 我可沒有要認輸的意思呢</span><br>Fucking EZ 簡単に惚れたの?笑<br><span class=\"zh-translate\">這麼輕易就喜歡上我了？笑</span><br>Low HP 恋したのかも<br><span class=\"zh-translate\">血量見底 也許是真的陷入愛河了也說不定</span><br>Toxic 生意気な口に Kiss me キスをして<br><span class=\"zh-translate\">帶著毒性 對這張傲嬌的嘴唇 吻下去吧</span>",
    "ytId": "kgAVoL49H3M",
    "date": "2026.08",
    "sourceTitle": "2026 8月",
    "coverImg": "img/monthly/2026/08.jpg",
    "url": "monthly.html#month-08"
  },
  {
    "type": "monthly",
    "name": "猫日",
    "artist": "suis from ヨルシカ",
    "desc": "TV動畫《貓與龍》片頭曲，由 suis 親自作詞、キタニタツヤ 作曲編曲，帶來夏日氛圍滿載的清爽曲風！",
    "ytId": "nvcVUq1g1z8",
    "date": "2026.07",
    "sourceTitle": "2026 7月",
    "coverImg": "img/monthly/2026/07.jpg",
    "url": "monthly.html#month-07"
  },
  {
    "type": "monthly",
    "name": "ホウキボシ",
    "artist": "ロクデナシ",
    "desc": "ロクデナシ 帶來的全新單曲，細膩傳遞如彗星般劃過夜空的感性歌聲與旋律。",
    "ytId": "p7TZdvXJRtk",
    "date": "2026.07",
    "sourceTitle": "2026 7月",
    "coverImg": "img/monthly/2026/07.jpg",
    "url": "monthly.html#month-07"
  },
  {
    "type": "monthly",
    "name": "Greedy!!",
    "artist": "NELKE",
    "desc": "NELKE 的全新活力單曲，充滿節奏感與魅力的現代流行搖滾節奏！",
    "ytId": "pK6iadnsSm8",
    "date": "2026.07",
    "sourceTitle": "2026 7月",
    "coverImg": "img/monthly/2026/07.jpg",
    "url": "monthly.html#month-07"
  },
  {
    "type": "monthly",
    "name": "夜鷹",
    "artist": "米津玄師",
    "desc": "電影《王者天下 魂之決戰》主題曲，米津玄師以宏大壯烈且深具渲染力的旋律再次震撼人心。",
    "ytId": "YjPMupS1Lg4",
    "date": "2026.07",
    "sourceTitle": "2026 7月",
    "coverImg": "img/monthly/2026/07.jpg",
    "url": "monthly.html#month-07"
  },
  {
    "type": "monthly",
    "name": "I-BULL",
    "artist": "jo0ji",
    "desc": "TV動畫《BLEACH 死神 千年血戰篇-禍進譚-》片頭曲，獨特獨白式的狂野嗓音與強烈吉他節奏劃破黑夜！",
    "ytId": "P31CxorjHjI",
    "date": "2026.07",
    "sourceTitle": "2026 7月",
    "coverImg": "img/monthly/2026/07.jpg",
    "url": "monthly.html#month-07"
  },
  {
    "type": "monthly",
    "name": "無花果煙",
    "artist": "ずっと真夜中でいいのに。",
    "desc": "TV動畫《在超市後門抽菸的兩人》片頭曲，ZUTOMAYO 標誌性的洗腦復古節奏與充滿故事感的歌詞演繹！",
    "ytId": "aOOwNK6Ul6E",
    "date": "2026.07",
    "sourceTitle": "2026 7月",
    "coverImg": "img/monthly/2026/07.jpg",
    "url": "monthly.html#month-07"
  },
  {
    "type": "monthly",
    "name": "烏",
    "artist": "米津玄師",
    "desc": "今だけは誰の声も聞こえない場所へ行こう<br><span class=\"zh-translate\">就這一次，去到聽不見任何人聲音的地方吧。</span><br>寄せ書きもそっと机にしまって澄み渡る青い方へ<br><span class=\"zh-translate\">將留言冊悄然鎖進桌屜，朝著澄澈湛藍的彼方遠去。</span><br>僕らは今日ただ一羽の夢見がちな烏になって<br><span class=\"zh-translate\">今天，我們化作一隻愛做夢的烏鴉。</span><br>光を受けて続くこの道を辿り直していく<br><span class=\"zh-translate\">沐浴在光中，重新踏上那條綿延的歸途。</span>",
    "ytId": "YjPMupS1Lg4",
    "date": "2026.06",
    "sourceTitle": "2026 6月",
    "coverImg": "img/monthly/2026/06.jpg",
    "url": "monthly-2026-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "プラネタリウム",
    "artist": "SHO-SENSEI!!",
    "desc": "永遠に僕と笑ってよ<br><span class=\"zh-translate\">永遠陪著我一起笑吧</span><br>どうせどうせこの世界に大切なものはそこまでないから<br><span class=\"zh-translate\">反正這個世界上，真正重要的東西本來就沒有那麼多</span><br>忘れられない人は忘れなくていい<br><span class=\"zh-translate\">那些無法忘記的人，就不必勉強自己遺忘</span><br>一緒にならきっと明日を待てるさ<br><span class=\"zh-translate\">只要有你在身邊，我們一定能一起等待明天的到來</span>",
    "ytId": "VfrIXXicc2w",
    "date": "2026.06",
    "sourceTitle": "2026 6月",
    "coverImg": "img/monthly/2026/06.jpg",
    "url": "monthly-2026-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "私の恋 is over",
    "artist": "春茶",
    "desc": "私の恋 is over それは真っ赤な色<br><span class=\"zh-translate\">我的戀情已經結束，那是一抹鮮紅的顏色</span><br>神様、どうか \"あなた\" 幸せにしてよね<br><span class=\"zh-translate\">神啊，請一定要讓「你」獲得幸福</span><br>好意 is over 涙が枯れる音<br><span class=\"zh-translate\">這份愛意已經結束，只剩下淚水流盡的聲音</span><br>わざとらしくね さよなら<br><span class=\"zh-translate\">故作瀟灑地，說聲再見吧</span><br>私、女の子だから<br><span class=\"zh-translate\">因為，我是個女孩子</span>",
    "ytId": "2i6C22fN_14",
    "date": "2026.06",
    "sourceTitle": "2026 6月",
    "coverImg": "img/monthly/2026/06.jpg",
    "url": "monthly-2026-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "SOS",
    "artist": "tuki.",
    "desc": "緊急事態だ僕ら拡声して歌う<br><span class=\"zh-translate\">緊急狀況，所以我們放聲高歌</span><br>愛の数が全然足りなすぎんだ<br><span class=\"zh-translate\">這世界上的愛，真的遠遠不夠</span><br>反芻心中じゃ痛み止まない<br><span class=\"zh-translate\">光是一再反覆咀嚼回憶，無法讓疼痛停止</span><br>全部を吐き出すんだ<br><span class=\"zh-translate\">把心裡的一切，全都喊出來吧</span><br>四方八方 叫んだ SOS が<br><span class=\"zh-translate\">朝著四面八方呼喊出的 SOS</span><br>一人じゃないよって誰かの希望なんです<br><span class=\"zh-translate\">會成為某個人「你並不孤單」的希望</span>",
    "ytId": "-23SgNWEAvM",
    "date": "2026.06",
    "sourceTitle": "2026 6月",
    "coverImg": "img/monthly/2026/06.jpg",
    "url": "monthly-2026-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "星をみる少女",
    "artist": "星街すいせい",
    "desc": "Star gazing 星をみる少女<br><span class=\"zh-translate\">Star gazing，仰望星空的少女</span><br>いたいけなあなたの瞳に<br><span class=\"zh-translate\">在你那純真無邪的眼眸裡</span><br>Star gazing まだ映ってますか<br><span class=\"zh-translate\">Star gazing，如今仍映照著星光嗎？</span><br>胸を張って会いに行けるように 今<br><span class=\"zh-translate\">為了能夠昂首胸膛地與你相見，從現在開始</span>",
    "ytId": "9ijHd0knEww",
    "date": "2026.06",
    "sourceTitle": "2026 6月",
    "coverImg": "img/monthly/2026/06.jpg",
    "url": "monthly-2026-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "一二三",
    "artist": "Penthouse",
    "desc": "動畫《入間同學入魔了！》第四季片頭曲，充滿魔性且旋律極其輕快洗腦的曲風！",
    "ytId": "pdcdLtdT98s",
    "date": "2026.05.TBA",
    "sourceTitle": "2026 5月",
    "coverImg": "img/monthly/2026/05.jpg",
    "url": "monthly-2026-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "誓い",
    "artist": "Leina",
    "desc": "電視動畫《日本三國》的片尾曲，以溫柔且深具穿透力的歌聲訴說著誓言。",
    "ytId": "1KnySdlZHJU",
    "date": "2026.05.TBA",
    "sourceTitle": "2026 5月",
    "coverImg": "img/monthly/2026/05.jpg",
    "url": "monthly-2026-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "しんそう",
    "artist": "KoRiN/重音テトSV",
    "desc": "來自台灣創作者的寶藏 V家原創歌曲，是在新一代設計展中無意間發現的超棒作品！",
    "ytId": "s5ftWy4sEeo",
    "date": "2026.05.TBA",
    "sourceTitle": "2026 5月",
    "coverImg": "img/monthly/2026/05.jpg",
    "url": "monthly-2026-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "閃光",
    "artist": "[Alexandros]",
    "desc": "動畫電影《機動戰士鋼彈 閃光的哈薩威》主題曲，強烈節奏與熱血感爆棚的搖滾神曲。",
    "ytId": "xfG6L9I7N8I",
    "date": "2026.05.TBA",
    "sourceTitle": "2026 5月",
    "coverImg": "img/monthly/2026/05.jpg",
    "url": "monthly-2026-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "CLASSIC",
    "artist": "Ayumu Imazu",
    "desc": "來自第二張個人專輯的主打歌。Ayumu Imazu 的新歌再次展現了他驚人的才華與極強的節奏感。",
    "ytId": "toD2V6Sohhc",
    "date": "2026.05.TBA",
    "sourceTitle": "2026 5月",
    "coverImg": "img/monthly/2026/05.jpg",
    "url": "monthly-2026-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "omoi",
    "artist": "音田雅則",
    "desc": "寫實且動人的抒情歌，描寫在深夜便利商店、副駕駛座等日常場景中，對重要之人最真摯的思念。",
    "ytId": "4gxZ_SVTk5c",
    "date": "2026.05.TBA",
    "sourceTitle": "2026 5月",
    "coverImg": "img/monthly/2026/05.jpg",
    "url": "monthly-2026-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "あぶく",
    "artist": "ヨルシカ",
    "desc": "ヨルシカ的最新作品<br>TVアニメ「LIAR GAME」OP<br>整首歌光是MV就值得好好細品",
    "ytId": "OHAjc-ayhus",
    "date": "2026.04.24",
    "sourceTitle": "2026 4月",
    "coverImg": "img/monthly/2026/04.jpg",
    "url": "monthly-2026-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "零",
    "artist": "tuki.(17)",
    "desc": "tuki.(17)的最新作品<br>融合了電子音樂與搖滾元素<br>MV的部分也很有意思<br>tuki本人在影片中呈現要露不露臉的樣貌<br>非常逗趣",
    "ytId": "iWeRglrNu6E",
    "date": "2026.04.27",
    "sourceTitle": "2026 4月",
    "coverImg": "img/monthly/2026/04.jpg",
    "url": "monthly-2026-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "言葉の続き",
    "artist": "ロクデナシ",
    "desc": "ロクデナシ這次再度與MIMI合作<br>呈現一如往常溫柔有力量的歌曲",
    "ytId": "S0WRUA8JewY",
    "date": "2026.04.08",
    "sourceTitle": "2026 4月",
    "coverImg": "img/monthly/2026/04.jpg",
    "url": "monthly-2026-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "れびてーしょん",
    "artist": "キタニタツヤ",
    "desc": "キタニタツヤ的新作品這次的MV是使用VRChat製作而成<br>作為TV動畫『NEEDY GIRL OVERDOSE』的主題曲使用",
    "ytId": "l7hbIgnyhe0",
    "date": "2026.04.26",
    "sourceTitle": "2026 4月",
    "coverImg": "img/monthly/2026/04.jpg",
    "url": "monthly-2026-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "風のアンセム",
    "artist": "Eve feat. suis",
    "desc": "意想不到的組合再次合體啦!!!Eve再度與suis合作<br>作為動畫TV「とんがり帽子のアトリエ」オープニングテーマ主題歌<br>兩位男高女高一同合唱<br>讓人雞皮疙瘩四起啊!!!",
    "ytId": "ySpIrrCmiCU",
    "date": "2026.04.24",
    "sourceTitle": "2026 4月",
    "coverImg": "img/monthly/2026/04.jpg",
    "url": "monthly-2026-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "キャリーバッグ",
    "artist": "Leina",
    "desc": "Leina<br>最近很喜歡的歌手<br>這首行李箱<br>講述了一個旅行人的心情<br>在放下行李廂的那一刻<br>看到箱中的物品<br>能不能讓你想到我呢?",
    "ytId": "q8yw02APPxc",
    "date": "2026.04.05",
    "sourceTitle": "2026 4月",
    "coverImg": "img/monthly/2026/04.jpg",
    "url": "monthly-2026-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "千鳥",
    "artist": "ヨルシカ",
    "desc": "勇蝶一鹿。",
    "ytId": "t75qlQPXJGw",
    "date": "2026.03.06",
    "sourceTitle": "2026 3月",
    "coverImg": "img/monthly/2026/03.jpg",
    "url": "monthly-2026-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "総体的独自論",
    "artist": "Daitch feat.汐菜",
    "desc": "曾經推薦過汐菜的空唄<br>這次讓我們來聽聽不一樣的她。",
    "ytId": "kY5OFSUoQq0",
    "date": "2022.11.30",
    "sourceTitle": "2026 3月",
    "coverImg": "img/monthly/2026/03.jpg",
    "url": "monthly-2026-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "サヨナラの合図",
    "artist": "みなとん",
    "desc": "講述了對於畢業的感受<br>既是期待亦有不捨<br>要進入下個階段<br>卻又懷念著現在",
    "ytId": "YUKhmzGPcaM",
    "date": "2026.02.19",
    "sourceTitle": "2026 3月",
    "coverImg": "img/monthly/2026/03.jpg",
    "url": "monthly-2026-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "プリマドンナ",
    "artist": "星街すいせい",
    "desc": "星街彗星<br>不多做解釋了<br>這首歌的MV真的很有趣<br>是以一個偶像的視角來呈現的<br>裡面有很多對偶像文化的諷刺和幽默<br>非常推薦大家去看看",
    "ytId": "M1GYqy0tHV0",
    "date": "2026.03.22",
    "sourceTitle": "2026 3月",
    "coverImg": "img/monthly/2026/03.jpg",
    "url": "monthly-2026-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "徹夜",
    "artist": "ZUTOMAYO",
    "desc": "Huluオリジナル「時計館の殺人」オープニング曲。大家最喜歡的真夜中來啦<br>熟悉的貝斯聲<br>需要細細品味的歌詞<br>都讓人想要反覆再聽",
    "ytId": "rsjaFk0Z5es",
    "date": "2026.03.05",
    "sourceTitle": "2026 3月",
    "coverImg": "img/monthly/2026/03.jpg",
    "url": "monthly-2026-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "ブレインロット",
    "artist": "東京真中feat. 重音テト",
    "desc": "由東京真中與重音テト合作的歌曲<br>後室迷因洗腦旋律加上那迷幻的舞步<br>你還座得住嗎?",
    "ytId": "UsjsYMo3O1Q",
    "date": "2026.02.25",
    "sourceTitle": "2026 3月",
    "coverImg": "img/monthly/2026/03.jpg",
    "url": "monthly-2026-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "プロポーズ",
    "artist": "9Lana cover",
    "desc": "最近發現的寶藏歌手9Lana!!<br>充滿爆發力的歌聲<br>一進副歌的轉音<br>你一定要來聽聽!!!",
    "ytId": "XPLkkdMFmco",
    "date": "2024.08.23",
    "sourceTitle": "2026 2月",
    "coverImg": "img/monthly/2026/02.jpg",
    "url": "monthly-2026-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "月が綺麗ねと言われたい！",
    "artist": "柿崎ユウタ",
    "desc": "月が綺麗ねと言われたい！在日文裡白話表示月亮很美<br>隱喻的意思則為我喜歡你!ㄋ",
    "ytId": "jorNAdLoRGg",
    "date": "2026.01.30",
    "sourceTitle": "2026 2月",
    "coverImg": "img/monthly/2026/02.jpg",
    "url": "monthly-2026-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "生活の",
    "artist": "ロクデナシ",
    "desc": "來自日本的溫柔女聲ロクデナシ<br>這首歌的MV是由MIMI負責的<br>整首歌講述著人與人之間的日常<br>在不知不覺中就習慣了對方<br>發現某天對方不在<br>才驚覺原來已經離不開了",
    "ytId": "sxaK-9eXmp8",
    "date": "2026.02.04",
    "sourceTitle": "2026 2月",
    "coverImg": "img/monthly/2026/02.jpg",
    "url": "monthly-2026-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "だから",
    "artist": "えんぷてい",
    "desc": "很日常的日系浪漫輕搖滾<br>MV的部分則是以一個男生的視角來呈現的<br>講述了他對於喜歡女生的心情<br>以及他們之間微妙的距離感",
    "ytId": "vDq4BiNbEmk",
    "date": "2026.01.21",
    "sourceTitle": "2026 2月",
    "coverImg": "img/monthly/2026/02.jpg",
    "url": "monthly-2026-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "コトノハ",
    "artist": "tuki.",
    "desc": "tuki到目前的作品匯集<br>MV敘述一路走來的心得<br>從一開始的迷茫到後來的成長<br>最後在MV的結尾處<br>tuki本人也有出現<br>讓人感受到tuki對於音樂的熱愛和堅持",
    "ytId": "Tu_Zvj-TRFA",
    "date": "2026.02.18",
    "sourceTitle": "2026 2月",
    "coverImg": "img/monthly/2026/02.jpg",
    "url": "monthly-2026-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "お姫様にはなれない",
    "artist": "ユイカ",
    "desc": "個人最喜歡的歌手ユイカ<br>這首以女生角度敘述<br>偶爾也像被像公主一樣對待阿",
    "ytId": "ic9XKLWMbCw",
    "date": "2026.02.TBA",
    "sourceTitle": "2026 2月",
    "coverImg": "img/monthly/2026/02.jpg",
    "url": "monthly-2026-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "MONTAGEM HIKARI",
    "artist": "BellyJay",
    "desc": "洗腦抓耳的旋律<br>讓我們在微光中從早跳到晚吧!!",
    "ytId": "1i5S2ZzmZ04",
    "date": "2026.02.TBA",
    "sourceTitle": "2026 2月",
    "coverImg": "img/monthly/2026/02.jpg",
    "url": "monthly-2026-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "AIZO",
    "artist": "King Gnu",
    "desc": "作為咒術迴戰死滅迴游的主題曲<br>King Gnu再次展現了他們獨特的音樂風格。動畫真的很燃阿",
    "ytId": "zz2a9Q2Wru0",
    "date": "2026.01.24",
    "sourceTitle": "2026 1月",
    "coverImg": "img/monthly/2026/01.jpg",
    "url": "monthly-2026-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "よあけのうた",
    "artist": "jo0ji",
    "desc": "大物新人jo0ji為咒術迴戰死滅迴游獻唱的ED曲<br>這首歌的旋律優美<br>歌詞也頗具深意<br>聽之後會有一種莫名溫暖",
    "ytId": "ufcDIOS1HRo",
    "date": "2026.01.09",
    "sourceTitle": "2026 1月",
    "coverImg": "img/monthly/2026/01.jpg",
    "url": "monthly-2026-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "世界が終わりました",
    "artist": "Yuuri",
    "desc": "Yuuri睽偉已久出的新歌<br>歌詞講述著沒有意識到對方是多麼重要的存在<br>直至失去才有所發現。",
    "ytId": "wTbrW044Tp0",
    "date": "2026.01.13",
    "sourceTitle": "2026 1月",
    "coverImg": "img/monthly/2026/01.jpg",
    "url": "monthly-2026-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "月に向かって撃て",
    "artist": "星街すいせい",
    "desc": "最近星街的歌都是像這樣充滿力量的搖滾曲風了<br>MV部分也採用大量3D<br>至於歌詞<br>讓大家自行體會了",
    "ytId": "DeAD2b1x3tQ",
    "date": "2026.01.07",
    "sourceTitle": "2026 1月",
    "coverImg": "img/monthly/2026/01.jpg",
    "url": "monthly-2026-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "アドレナ",
    "artist": "YOASOBI",
    "desc": "作為「花樣少年少女」OP主題曲<br>YOASOBI這次也是強勢出擊<br>這首歌的旋律充滿了青春的活力<br>歌詞則講述了青春期的迷茫和成長<br>非常適合這部動畫的主題",
    "ytId": "NKhw0qOLMms",
    "date": "2026.01.03",
    "sourceTitle": "2026 1月",
    "coverImg": "img/monthly/2026/01.jpg",
    "url": "monthly-2026-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "セレナーデ",
    "artist": "なとり",
    "desc": "なとり為《我推的孩子》獻唱的ED曲<br>除了非常契合原本動畫的主題外<br>也非常有なとり本人的色彩<br>沒有我的人生<br>也要好好地幸福下去!",
    "ytId": "gNg2Qw5R-Q4",
    "date": "2026.01.21",
    "sourceTitle": "2026 1月",
    "coverImg": "img/monthly/2026/01.jpg",
    "url": "monthly-2026-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "Underdog",
    "artist": "Eve",
    "desc": "Eve的最新單曲<br>這次的MV及CC字幕都別具特色動畫部分 MV 則由 OFF SCRIPT 負責製作。",
    "ytId": "UfTpKaKXbG4",
    "date": "2025.11.28",
    "sourceTitle": "2025 12月",
    "coverImg": "img/monthly/2025/12.jpg",
    "url": "monthly-2025-h2.html#month-12"
  },
  {
    "type": "monthly",
    "name": "I'm a loner",
    "artist": "정용화×優里",
    "desc": "優里以及鄭容和意想不到的組合<br>以鄭容和知名歌曲《I'm a Loner》配上優里重新詮釋這首歌",
    "ytId": "UwmwAECBkwg",
    "date": "2025.12.12",
    "sourceTitle": "2025 12月",
    "coverImg": "img/monthly/2025/12.jpg",
    "url": "monthly-2025-h2.html#month-12"
  },
  {
    "type": "monthly",
    "name": "DUET",
    "artist": "ZICOxikura",
    "desc": "同樣也是意想不到的組合<br>ZICO與ikura的合作單曲<br>歌詞巧妙穿插日韓英三國語言<br>旋律、舞蹈一氣呵成。",
    "ytId": "sssoyDLFPWE",
    "date": "2025.12.18",
    "sourceTitle": "2025 12月",
    "coverImg": "img/monthly/2025/12.jpg",
    "url": "monthly-2025-h2.html#month-12"
  },
  {
    "type": "monthly",
    "name": "彗星",
    "artist": "星街すいせい",
    "desc": "星街すいせい的最新單曲<br>以彗星為主題<br>展現了她獨特的音樂風格和視覺效果。",
    "ytId": "1YrG2WGeIJo",
    "date": "2025.12.05",
    "sourceTitle": "2025 12月",
    "coverImg": "img/monthly/2025/12.jpg",
    "url": "monthly-2025-h2.html#month-12"
  },
  {
    "type": "monthly",
    "name": "八月、某、月明かり",
    "artist": "ヨルシカ",
    "desc": "ヨルシカ的最新單曲<br>以八月和月光為主題。。",
    "ytId": "Vs5NViM8TSY",
    "date": "2025.12.15",
    "sourceTitle": "2025 12月",
    "coverImg": "img/monthly/2025/12.jpg",
    "url": "monthly-2025-h2.html#month-12"
  },
  {
    "type": "monthly",
    "name": "私が選んだもの",
    "artist": "ユイカ",
    "desc": "ユイカ<br>與過往歌曲相比<br>這首私が選んだもの更像是要相信自己的選擇<br>不要迷惘的持續前進。",
    "ytId": "d8coIl7ARZc",
    "date": "2025.12.10",
    "sourceTitle": "2025 12月",
    "coverImg": "img/monthly/2025/12.jpg",
    "url": "monthly-2025-h2.html#month-12"
  },
  {
    "type": "monthly",
    "name": "鯨の落ちる街",
    "artist": "ロクデナシ",
    "desc": "這次ロクデナシ的新單曲<br>這次的編曲MV作詞是由まふまふ負責<br>已在星際中遨遊的鯨魚為主軸<br>充滿著幻想及浩瀚無垠的未來。",
    "ytId": "7iVgomOU4Kk",
    "date": "2025.12.07",
    "sourceTitle": "2025 12月",
    "coverImg": "img/monthly/2025/12.jpg",
    "url": "monthly-2025-h2.html#month-12"
  },
  {
    "type": "monthly",
    "name": "アイオライト",
    "artist": "Eve",
    "desc": "Eve延續著《心海》《群青讚歌》的世界觀風格創作出的歌<br>青春氣息非常濃厚",
    "ytId": "l96CCKCktOU",
    "date": "2025.11.01",
    "sourceTitle": "2025 11月",
    "coverImg": "img/monthly/2025/11.jpg",
    "url": "monthly-2025-h2.html#month-11"
  },
  {
    "type": "monthly",
    "name": "痛いの痛いの飛んでいけっ",
    "artist": "MIMI feat. saewool",
    "desc": "這首歌痛いの痛いの飛んでいけっ中文翻譯意為痛痛快飛走搭配MIMI甜美可愛的歌聲<br>是讓人會覺得被療育的歌曲。",
    "ytId": "wW1UjAtAZ1A",
    "date": "2025.11.04",
    "sourceTitle": "2025 11月",
    "coverImg": "img/monthly/2025/11.jpg",
    "url": "monthly-2025-h2.html#month-11"
  },
  {
    "type": "monthly",
    "name": "最低な君に贈る歌",
    "artist": "優里",
    "desc": "沒錯!又是我優里大哥的歌<br>這首歌是優里在2025年11月13日發行的單曲<br>這首歌的歌詞充滿了對於愛情的矛盾和掙扎<br>至於MV部分則是呈現了很多樣性愛情的模樣。",
    "ytId": "0S3fU2p11Ic",
    "date": "2025.11.13",
    "sourceTitle": "2025 11月",
    "coverImg": "img/monthly/2025/11.jpg",
    "url": "monthly-2025-h2.html#month-11"
  },
  {
    "type": "monthly",
    "name": "Lip Noise",
    "artist": "TOMOO",
    "desc": "大家對於TOMOO的印象可能還停留在他之前的作品<br>這次的Lip Noise是TOMOO<br>從歌名可以看出跟過往風格的差異<br>編曲部分也不是傳統的ABABCB<br>非常期待大家能多關注這位有潛力的歌手。",
    "ytId": "CI_WJ7_kVnA",
    "date": "2025.11.12",
    "sourceTitle": "2025 11月",
    "coverImg": "img/monthly/2025/11.jpg",
    "url": "monthly-2025-h2.html#month-11"
  },
  {
    "type": "monthly",
    "name": "カロン",
    "artist": "ロクデナシ",
    "desc": "日劇殺死奪走女兒性命的人有罪嗎？片頭曲<br>整首歌以快節奏<br>講述著所謂的「殺人犯」的內心世界<br>從他們的角度來看待這個事件<br>讓人不禁思考起這個問題。",
    "ytId": "Okz5mY2dMDE",
    "date": "2025.11.21",
    "sourceTitle": "2025 11月",
    "coverImg": "img/monthly/2025/11.jpg",
    "url": "monthly-2025-h2.html#month-11"
  },
  {
    "type": "monthly",
    "name": "Darma Grand Prix",
    "artist": "RADWIMPS cover by.ヨルシカ",
    "desc": "為了慶祝RADWIMPS出道二十周年<br>ヨルシカ翻唱了RADWIMPS的歌曲Darma Grand Prix<br>這首歌原本是RADWIMPS在2011年發行的專輯《絶体絶命》中的一首歌曲<br>這次由ヨルシカ重新詮釋<br>帶來了不同的感覺。",
    "ytId": "equ1fkz9ZDE",
    "date": "2025.11.18",
    "sourceTitle": "2025 11月",
    "coverImg": "img/monthly/2025/11.jpg",
    "url": "monthly-2025-h2.html#month-11"
  },
  {
    "type": "monthly",
    "name": "まじかるちいかわ",
    "artist": "yama",
    "desc": "yama為吉伊卡哇所演唱的夢幻主題曲<br>風格可愛天真無邪<br>卻又不失yama本人的演唱功力。",
    "ytId": "NvDkY-yabC4",
    "date": "2025.10.21",
    "sourceTitle": "2025 10月",
    "coverImg": "img/monthly/2025/10.jpg",
    "url": "monthly-2025-h2.html#month-10"
  },
  {
    "type": "monthly",
    "name": "1991",
    "artist": "米津玄師",
    "desc": "米津玄師為電影《秒速五公分》所量身打造的歌曲<br>歌詞巧妙運用91的英文與日文發音的泣いて類似。",
    "ytId": "1cnndBdzCAk",
    "date": "2025.10.15",
    "sourceTitle": "2025 10月",
    "coverImg": "img/monthly/2025/10.jpg",
    "url": "monthly-2025-h2.html#month-10"
  },
  {
    "type": "monthly",
    "name": "Actor",
    "artist": "幾田りら",
    "desc": "人人都是盛裝起舞的演員。這是幾田りら為動漫《SPY×FAMILY》第二季所創作的片頭曲<br>歌詞充滿了角色內心世界和對於表面與真實之間的探討。",
    "ytId": "CPgu3rKZIBw",
    "date": "2025.10.10",
    "sourceTitle": "2025 10月",
    "coverImg": "img/monthly/2025/10.jpg",
    "url": "monthly-2025-h2.html#month-10"
  },
  {
    "type": "monthly",
    "name": "劇上",
    "artist": "YOASOBI",
    "desc": "這是少數YOASOBI本人有參與MV的歌曲。每個人都是舞台劇上的演員<br>請最認真的進行舞蹈吧",
    "ytId": "GuIkxXiVHps",
    "date": "2025.10.08",
    "sourceTitle": "2025 10月",
    "coverImg": "img/monthly/2025/10.jpg",
    "url": "monthly-2025-h2.html#month-10"
  },
  {
    "type": "monthly",
    "name": "妄想感傷代償連盟",
    "artist": "Myuk cover.",
    "desc": "Myuk<br>你可能不記得她的名字<br>但你一定要聽過她獨特的嗓音<br>阿姨壓一壓。",
    "ytId": "zGoQk-rU-po",
    "date": "2023.05.23",
    "sourceTitle": "2025 10月",
    "coverImg": "img/monthly/2025/10.jpg",
    "url": "monthly-2025-h2.html#month-10"
  },
  {
    "type": "monthly",
    "name": "人生讃歌",
    "artist": "tuki.",
    "desc": "tuki.的代表作之一<br>歌詞充滿了對於人生的思考和感悟。",
    "ytId": "epFQODCxlxA",
    "date": "2025.10.22",
    "sourceTitle": "2025 10月",
    "coverImg": "img/monthly/2025/10.jpg",
    "url": "monthly-2025-h2.html#month-10"
  },
  {
    "type": "monthly",
    "name": "IRIS OUT",
    "artist": "米津玄師",
    "desc": "為鏈鋸人電影版蕾潔篇創作的主題曲<br>極其洗腦的旋律<br>彷彿蕾潔與淀治在一旁戰鬥<br>沒看過電影的也不推薦去看<br>哭的話我不負責任",
    "ytId": "LmZD-TU96q4",
    "date": "2025.09.15",
    "sourceTitle": "2025 9月",
    "coverImg": "img/monthly/2025/09.jpg",
    "url": "monthly-2025-h2.html#month-09"
  },
  {
    "type": "monthly",
    "name": "斑色",
    "artist": "コバソロfeat. 由 -iu-",
    "desc": "由コバソロ與由 -iu-合作的單曲<br>講述了一個人的心境變化<br>不是什麼戲劇般的故事<br>搖搖晃晃、不完美的自己就可",
    "ytId": "kRjF5p0_Qkk",
    "date": "2025.08.08",
    "sourceTitle": "2025 9月",
    "coverImg": "img/monthly/2025/09.jpg",
    "url": "monthly-2025-h2.html#month-09"
  },
  {
    "type": "monthly",
    "name": "DEADPOOL゚",
    "artist": "星街彗星feat. 花譜",
    "desc": "星街彗星與花譜的夢幻連動<br>整首歌輕快<br>雖充滿自我懷疑的歌詞<br>但卻又帶有一種積極向上的力量<br>讓人聽了之後會覺得自己也能夠克服困難<br>繼續前進。",
    "ytId": "Fg5-55vZwp0",
    "date": "2025.01.21",
    "sourceTitle": "2025 9月",
    "coverImg": "img/monthly/2025/09.jpg",
    "url": "monthly-2025-h2.html#month-09"
  },
  {
    "type": "monthly",
    "name": "輪廻転生",
    "artist": "優里",
    "desc": "恩對已經連續好幾個月都有出新歌的優里<br>歌詞講述著沒有人能定義你<br>你就是自己生命中的主宰!不要放棄的向前吧",
    "ytId": "Rrn66Gp8apo",
    "date": "2025.09.05",
    "sourceTitle": "2025 9月",
    "coverImg": "img/monthly/2025/09.jpg",
    "url": "monthly-2025-h2.html#month-09"
  },
  {
    "type": "monthly",
    "name": "我慢するのに疲れた日も",
    "artist": "Shiori Shinomiya",
    "desc": "神秘企劃的第一首歌<br>Shiori Shinomiya的最新單曲<br>歌詞充滿了對於生活中壓力和疲憊的描寫<br>所以大聲地嘶吼吧",
    "ytId": "NokXQrdCZRY",
    "date": "2025.08.15",
    "sourceTitle": "2025 9月",
    "coverImg": "img/monthly/2025/09.jpg",
    "url": "monthly-2025-h2.html#month-09"
  },
  {
    "type": "monthly",
    "name": "ウォーアイニー",
    "artist": "水曜日のカンパネラ",
    "desc": "TV「らんま1/2」的主題曲<br>主唱詩羽獨特造型以及甜美的聲線<br>配上東方風格的歌詞<br>讓整首歌都很抓耳且想讓人一同歌唱",
    "ytId": "RwRDJkriXU4",
    "date": "2025.09.24",
    "sourceTitle": "2025 9月",
    "coverImg": "img/monthly/2025/09.jpg",
    "url": "monthly-2025-h2.html#month-09"
  },
  {
    "type": "monthly",
    "name": "ローズヒップティー",
    "artist": "ユイカ",
    "desc": "少女複雜的心情<br>透過假裝討厭但內心其實是很喜歡對方對自己的行為",
    "ytId": "q3bPSDVOIxs",
    "date": "2025.09.25",
    "sourceTitle": "2025 9月",
    "coverImg": "img/monthly/2025/09.jpg",
    "url": "monthly-2025-h2.html#month-09"
  },
  {
    "type": "monthly",
    "name": "織姫とBABY",
    "artist": "ねぐせ。feat. 汐れいら",
    "desc": "七夕必聽<br>由ねぐせ。與汐れいら合作的單曲<br>歌詞講述了織姬和牛郎的故事<br>讓我們一同大笑彼此擁抱",
    "ytId": "RyviHjvLIao",
    "date": "2025.06.22",
    "sourceTitle": "2025 8月",
    "coverImg": "img/monthly/2025/08.jpg",
    "url": "monthly-2025-h2.html#month-08"
  },
  {
    "type": "monthly",
    "name": "ふたりぼっちの世界",
    "artist": "miolly",
    "desc": "彼此殘缺的部分<br>就由兩人一起填補吧<br>如同歌名所示<br>這首歌講述了兩個人一起面對孤獨和困難的故事<br>充滿了溫暖和希望。",
    "ytId": "Dn7U3JAerm4",
    "date": "2025.03.09",
    "sourceTitle": "2025 8月",
    "coverImg": "img/monthly/2025/08.jpg",
    "url": "monthly-2025-h2.html#month-08"
  },
  {
    "type": "monthly",
    "name": "ループ",
    "artist": "slept.",
    "desc": "沉溺在與你共度的夜晚裡<br>連那麼討厭的早晨也能跨越<br>講述著感情<br>卻以輕快的旋律來表達日常的種種",
    "ytId": "U44PcldKDh8",
    "date": "2025.07.09",
    "sourceTitle": "2025 8月",
    "coverImg": "img/monthly/2025/08.jpg",
    "url": "monthly-2025-h2.html#month-08"
  },
  {
    "type": "monthly",
    "name": "太陽が昇らない世界",
    "artist": "Aimer",
    "desc": "Aimer好久不見!!!為『劇場版「鬼滅の刃」無限城編 』第一章 猗窩座再来』 主題歌<br>大哥...沒有書",
    "ytId": "DJOf0XtVpkI",
    "date": "2025.07.24",
    "sourceTitle": "2025 8月",
    "coverImg": "img/monthly/2025/08.jpg",
    "url": "monthly-2025-h2.html#month-08"
  },
  {
    "type": "monthly",
    "name": "修羅",
    "artist": "ヨルシカ",
    "desc": "ヨルシカ<br>MV的呈現非常有趣<br>這個部份希望由你們自行體會",
    "ytId": "h4F-q-R67H0",
    "date": "2025.08.21",
    "sourceTitle": "2025 8月",
    "coverImg": "img/monthly/2025/08.jpg",
    "url": "monthly-2025-h2.html#month-08"
  },
  {
    "type": "monthly",
    "name": "イオ",
    "artist": "ロクデナシ",
    "desc": "擅長使用星座來寫歌的樂團ロクデナシ 這次帶來新的作品IO“Io”是一顆衛星的名字<br>但用漢字寫出來是“五百 (io)”<br>意思是“非常大的數字”此外<br>也有諧音的意思<br>讓各位自行去發掘搂。",
    "ytId": "RjhLcPQ2EWg",
    "date": "2025.08.27",
    "sourceTitle": "2025 8月",
    "coverImg": "img/monthly/2025/08.jpg",
    "url": "monthly-2025-h2.html#month-08"
  },
  {
    "type": "monthly",
    "name": "夏の影",
    "artist": "Mrs. GREEN APPLE",
    "desc": "樂團Mrs. GREEN APPLE為「午後の紅茶」2025年夏季廣告所創作的歌曲<br>歌詞描繪了夏日午後的悠閒氛圍和對於美好時光的珍惜。",
    "ytId": "-p3O35mfSB4",
    "date": "2025.08.11",
    "sourceTitle": "2025 8月",
    "coverImg": "img/monthly/2025/08.jpg",
    "url": "monthly-2025-h2.html#month-08"
  },
  {
    "type": "monthly",
    "name": "モエチャッカファイア",
    "artist": "若山詩音cover",
    "desc": "鯊魚娘<br>由聲優本人獻唱的歌曲<br>同時作為遊戲《絕區零》一周年歌曲<br>整首敘述帶傲嬌屬性配上有趣的歌詞",
    "ytId": "rTqYRWcA-Yw",
    "date": "2025.07.06",
    "sourceTitle": "2025 7月",
    "coverImg": "img/monthly/2025/07.jpg",
    "url": "monthly-2025-h2.html#month-07"
  },
  {
    "type": "monthly",
    "name": "革命道中",
    "artist": "アイナ・ジ・エンド",
    "desc": "為膽大黨第二季初的歌曲<br>不是新人但令人驚艷<br>主唱充滿爆發接近嘶吼的聲音<br>你怎麼能不喜歡",
    "ytId": "NLIGDjKBLY0",
    "date": "2025.07.03",
    "sourceTitle": "2025 7月",
    "coverImg": "img/monthly/2025/07.jpg",
    "url": "monthly-2025-h2.html#month-07"
  },
  {
    "type": "monthly",
    "name": "ラストルック",
    "artist": "須田景凪",
    "desc": "作為TV 動畫「暗殺教室」再放送 第2弾<br>從理事長的角度來看這首歌<br>感覺非常貼切<br>另外<br>MV沒有提到請《注意閃光燈!!》",
    "ytId": "pkMBduvJJdQ",
    "date": "2025.07.16",
    "sourceTitle": "2025 7月",
    "coverImg": "img/monthly/2025/07.jpg",
    "url": "monthly-2025-h2.html#month-07"
  },
  {
    "type": "monthly",
    "name": "雨景色",
    "artist": "ロクデナシ",
    "desc": "歌詞敘述著愛情就像雨一樣<br>時而溫柔<br>時而猛烈<br>讓人無法預測和掌控<br>但同時也帶來了生命的滋潤和成長<br>就像雨水滋養大地一樣<br>愛情也能讓人變得更好。",
    "ytId": "TfZUcD7mwck",
    "date": "2025.07.23",
    "sourceTitle": "2025 7月",
    "coverImg": "img/monthly/2025/07.jpg",
    "url": "monthly-2025-h2.html#month-07"
  },
  {
    "type": "monthly",
    "name": "ねっくれすが錆びる前に",
    "artist": "琳子",
    "desc": "用那種嗓音唱傷感情歌<br>簡單來說<br>作弊",
    "ytId": "9Jq2toTQ8M4",
    "date": "2025.07.19",
    "sourceTitle": "2025 7月",
    "coverImg": "img/monthly/2025/07.jpg",
    "url": "monthly-2025-h2.html#month-07"
  },
  {
    "type": "monthly",
    "name": "ハッピーラッキーチャッピー",
    "artist": "ano",
    "desc": "全能型女演員ano這次為動畫『タコピーの原罪』獻唱OP<br>整首致鬱的動漫<br>卻用歡快的歌聲旋律帶過<br>十分契合原作想傳達的感受。",
    "ytId": "s7FgdaGOw9s",
    "date": "2025.07.19",
    "sourceTitle": "2025 7月",
    "coverImg": "img/monthly/2025/07.jpg",
    "url": "monthly-2025-h2.html#month-07"
  },
  {
    "type": "monthly",
    "name": "恋風",
    "artist": "幾田りら",
    "desc": "幾田りら<br>歌詞描寫了夏日的風像是倏忽而過的戀情<br>整首歌聽了心情相當放鬆。",
    "ytId": "bWlknrhWjVw",
    "date": "2025.06.09",
    "sourceTitle": "2025 6月",
    "coverImg": "img/monthly/2025/06.jpg",
    "url": "monthly-2025-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "全身前礼",
    "artist": "AKASAKI",
    "desc": "AKASAKI難得魔性不按常理出招一次<br>這首歌的旋律和歌詞都充滿了夏日的氛圍<br>讓人聽了就想去海邊玩水。",
    "ytId": "7jCUtWcd-9k",
    "date": "2025.06.11",
    "sourceTitle": "2025 6月",
    "coverImg": "img/monthly/2025/06.jpg",
    "url": "monthly-2025-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "HALO",
    "artist": "NOMELON NOLEMON",
    "desc": "樂團NOMELON NOLEMON為TV動畫「機動戦士Gundam GQuuuuuuX」的挿入歌<br>我想把一切都歸咎於昨晚<br>然後忘掉它<br>但即使我閉上眼睛<br>你的身影依然揮之不去<br>讓我無法入睡。",
    "ytId": "dDAP5OQv2RA",
    "date": "2025.05.21",
    "sourceTitle": "2025 6月",
    "coverImg": "img/monthly/2025/06.jpg",
    "url": "monthly-2025-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "プロポーズ",
    "artist": "なとり",
    "desc": "恭喜這首榮登我個人最愛<br>歌詞敘述著再怎麼努力<br>其實我也就只是一般人<br>但無論怎麼想<br>我都為你著迷",
    "ytId": "VDdLF1YubI0",
    "date": "2025.06.06",
    "sourceTitle": "2025 6月",
    "coverImg": "img/monthly/2025/06.jpg",
    "url": "monthly-2025-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "Hachikō",
    "artist": "Fujii Kaze",
    "desc": "藤井風以忠犬八公的故事為靈感創作的歌曲<br>歌詞描繪了八公對主人的忠誠和愛<br>一直耐心地守候著我<br>我們要去哪裡呢<br>忠犬八公？",
    "ytId": "OodEsjZ88TQ",
    "date": "2025.06.13",
    "sourceTitle": "2025 6月",
    "coverImg": "img/monthly/2025/06.jpg",
    "url": "monthly-2025-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "cosmos",
    "artist": "Awesome City Club",
    "desc": "親愛的<br>親愛的<br>就到此為止吧<br>樂團Awesome City Club的這首歌<br>歌詞描繪了一段感情的結束<br>雖然曾經美好<br>但現在已經無法繼續下去。",
    "ytId": "LgIoqxvwnVA",
    "date": "2025.06.18",
    "sourceTitle": "2025 6月",
    "coverImg": "img/monthly/2025/06.jpg",
    "url": "monthly-2025-h1.html#month-06"
  },
  {
    "type": "monthly",
    "name": "脈拍",
    "artist": "ロクデナシ",
    "desc": "你的臉，你的聲音，每當我觸碰，就感到痛苦。",
    "ytId": "wkRMEv1LcNs",
    "date": "2025.05.07",
    "sourceTitle": "2025 5月",
    "coverImg": "img/monthly/2025/05.jpg",
    "url": "monthly-2025-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "綺麗事",
    "artist": "星街すいせい/",
    "desc": "想保持著美麗，結果卻讓真正的自己變得無法看清，星街的新歌「綺麗事」描繪了這種矛盾的心情",
    "ytId": "VPhLXeU25KA",
    "date": "2025.05.19",
    "sourceTitle": "2025 5月",
    "coverImg": "img/monthly/2025/05.jpg",
    "url": "monthly-2025-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "Watch me!",
    "artist": "YOASOBI",
    "desc": "YOASOBI為TV動畫『ウィッチウォッチ』獻唱的主題曲，這樣的日復一日，從那天起，我就愛上了你",
    "ytId": "evtoG-4dLM4",
    "date": "2025.05.18",
    "sourceTitle": "2025 5月",
    "coverImg": "img/monthly/2025/05.jpg",
    "url": "monthly-2025-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "feel like",
    "artist": "Eve",
    "desc": "好久不見的Eve，那時的我們，什麼都不是，卻像是昨天才發生的事一樣，希望你也能想起來就好了，也許我們認知到的日常，有一天會以某種形式消失不見吧",
    "ytId": "AGfC3lCFPRM",
    "date": "2025.05.23",
    "sourceTitle": "2025 5月",
    "coverImg": "img/monthly/2025/05.jpg",
    "url": "monthly-2025-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "プレデター",
    "artist": "AKASAKI",
    "desc": "你就像掠食者般，當你在我身邊時，我的心就怦然跳動",
    "ytId": "hFwtacZrH54",
    "date": "2025.05.14",
    "sourceTitle": "2025 5月",
    "coverImg": "img/monthly/2025/05.jpg",
    "url": "monthly-2025-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "クリームで会いにいけますか ",
    "artist": "ずっと真夜中でいいのに",
    "desc": "能用奶油來見你嗎？我什麼都不是，對於創造，也沒有對錯之分，ずっと真夜中でいいのに，神秘的世界觀和獨特的音樂風格，這首歌的歌詞充滿了詩意和隱喻，歡迎來到真夜中的世界。",
    "ytId": "JQ2913bVo30",
    "date": "2025.05.22",
    "sourceTitle": "2025 5月",
    "coverImg": "img/monthly/2025/05.jpg",
    "url": "monthly-2025-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "Room",
    "artist": "esoragoto",
    "desc": "連隨波逐流都辦不到的我，只想保持我自己原本的樣子",
    "ytId": "kaVKflzixbM",
    "date": "2025.05.12",
    "sourceTitle": "2025 5月",
    "coverImg": "img/monthly/2025/05.jpg",
    "url": "monthly-2025-h1.html#month-05"
  },
  {
    "type": "monthly",
    "name": "徘徊",
    "artist": "AKASAKI",
    "desc": "在夜晚徘徊著，唯有你綻放得如此燦爛，愛AKASAKI",
    "ytId": "lcsOdkPICuQ",
    "date": "2025.04.16",
    "sourceTitle": "2025 4月",
    "coverImg": "img/monthly/2025/04.jpg",
    "url": "monthly-2025-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "最&強",
    "artist": "優里",
    "desc": "我們就像超級賽亞人一樣，無數次、幾十次幾百次地超越自己，非常有力量的一首歌",
    "ytId": "EQc6VzXE3CA",
    "date": "2025.04.21",
    "sourceTitle": "2025 4月",
    "coverImg": "img/monthly/2025/04.jpg",
    "url": "monthly-2025-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "騙シ愛",
    "artist": "tuki.",
    "desc": "在欺騙與愛的謊言之中，尋找能相信的東西，tuki.的這首歌描繪了在愛情中面對欺騙和不信任的掙扎，歌詞充滿了矛盾和痛苦的情感，很難讓人相信這是一個高中生年紀的人會寫出來的歌詞",
    "ytId": "l5K9exFxEnI",
    "date": "2025.04.13",
    "sourceTitle": "2025 4月",
    "coverImg": "img/monthly/2025/04.jpg",
    "url": "monthly-2025-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "微熱魔",
    "artist": "ZUTOMAYO",
    "desc": "TV動畫『阿波連さんははかれない season2』，總有一天會明白，令人安心，又令人緊張，這奇妙的人生",
    "ytId": "plpVOHqh3lA",
    "date": "2025.04.18",
    "sourceTitle": "2025 4月",
    "coverImg": "img/monthly/2025/04.jpg",
    "url": "monthly-2025-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "もうどうなってもいいや",
    "artist": "星街すいせい",
    "desc": "作為動畫《機動戦士Gundam GQuuuuuuX》 エンディングテーマ插入曲，“無論結局如何，都是美好的結局。",
    "ytId": "ojZaWERcbaI",
    "date": "2025.04.21",
    "sourceTitle": "2025 4月",
    "coverImg": "img/monthly/2025/04.jpg",
    "url": "monthly-2025-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "夏時幽靈",
    "artist": "星期三的康帕內拉",
    "desc": "不斷地重複 再重複，即使在這個世界裡，我仍要做我自己。",
    "ytId": "fbZv-X-1hCQ",
    "date": "2025.04.03",
    "sourceTitle": "2025 4月",
    "coverImg": "img/monthly/2025/04.jpg",
    "url": "monthly-2025-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "SPEED",
    "artist": "なとり",
    "desc": "只為了這瞬間掙扎也沒有意義，朝著現在能看到的地方前進吧",
    "ytId": "r2BbUBSWBAM",
    "date": "2025.04.25",
    "sourceTitle": "2025 4月",
    "coverImg": "img/monthly/2025/04.jpg",
    "url": "monthly-2025-h1.html#month-04"
  },
  {
    "type": "monthly",
    "name": "BOW AND ARROW",
    "artist": "米津玄師",
    "desc": "抓住未來，超越所有期待<br>總有一天，屬於你的光芒，會讓所有人都為之驚嘆<br>為動畫《金牌得主》所寫的主題曲<br>米津玄師今年感覺無極限了",
    "ytId": "M-Eyhjkepy0",
    "date": "2025.03.05",
    "sourceTitle": "2025 3月",
    "coverImg": "img/monthly/2025/03.jpg",
    "url": "monthly-2025-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "怪獣",
    "artist": "サカナクション",
    "desc": "為動畫『チ。 ―地球の運動について―』オープニング曲<br>日本團體魚韻帶來旋律很獨特的歌<br>不斷累積的音符，就像是劇中那樣<br>為探求知識，而不斷堆疊的深度",
    "ytId": "a8dgNdJVluc",
    "date": "2025.03.15",
    "sourceTitle": "2025 3月",
    "coverImg": "img/monthly/2025/03.jpg",
    "url": "monthly-2025-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "恋愛後遺症",
    "artist": "7co",
    "desc": "每天都像是日常的重複，卻又充滿了不確定性<br>7co的這首歌描繪了戀愛中的後遺症<br>當你以為已經習慣了對方的存在，卻又突然發現自己無法適應沒有對方的生活",
    "ytId": "u4HdDKDjqG4",
    "date": "2025.03.07",
    "sourceTitle": "2025 3月",
    "coverImg": "img/monthly/2025/03.jpg",
    "url": "monthly-2025-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "Caramel Pain",
    "artist": "星街すいせい",
    "desc": "這首歌我想，如果是設計系的同學看了應該會很有感觸。",
    "ytId": "UpEPkPg8YP4",
    "date": "2025.03.22",
    "sourceTitle": "2025 3月",
    "coverImg": "img/monthly/2025/03.jpg",
    "url": "monthly-2025-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "fortnight",
    "artist": "eill",
    "desc": "即便害怕，也能邁向明天<br>我們將永遠向前",
    "ytId": "hrmvj-H-wrs",
    "date": "2025.03.21",
    "sourceTitle": "2025 3月",
    "coverImg": "img/monthly/2025/03.jpg",
    "url": "monthly-2025-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "片想い",
    "artist": "SUPERBEAVER",
    "desc": "SUPER BEAVER的這首歌，描繪了單戀的心情<br>當你喜歡一個人，但又無法表達出來，只能默默地守護著對方<br>這種感覺既甜蜜又痛苦",
    "ytId": "IGC9c8ezbQA",
    "date": "2025.03.24",
    "sourceTitle": "2025 3月",
    "coverImg": "img/monthly/2025/03.jpg",
    "url": "monthly-2025-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "さよならになりました",
    "artist": "Chevon",
    "desc": "我想變得幸福，哪怕只是一點點",
    "ytId": "jQIoj7fb1ZI",
    "date": "2025.03.26",
    "sourceTitle": "2025 3月",
    "coverImg": "img/monthly/2025/03.jpg",
    "url": "monthly-2025-h1.html#month-03"
  },
  {
    "type": "monthly",
    "name": "Orbital Period",
    "artist": "星街すいせい",
    "desc": "這首歌對星街或是粉絲的我們而言都非常有意義<br>歌詞描繪了星街從出道以來的心路歷程<br>從一開始的迷茫和不安，到後來的成長和自信<br>這首歌讓人聽了非常感動，甚至會起雞皮疙瘩，終於唱進武道館啦!!!",
    "ytId": "jMSXPPSmsVo",
    "date": "2025.02.02",
    "sourceTitle": "2025 2月",
    "coverImg": "img/monthly/2025/02.jpg",
    "url": "monthly-2025-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "BURN",
    "artist": "yama✕WurtS",
    "desc": "作為TV動畫『るろうに剣心－明治剣客浪漫譚－ 京都動乱』第2クールオープニング・テーマ<br>整首都很熱血不論幾次就這樣燃燒起來",
    "ytId": "H-Ll5b5NVYA",
    "date": "2025.02.08",
    "sourceTitle": "2025 2月",
    "coverImg": "img/monthly/2025/02.jpg",
    "url": "monthly-2025-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "Snake",
    "artist": "ヨルシカ",
    "desc": "",
    "ytId": "NfxKuAHDC3s",
    "date": "2025.01.06",
    "sourceTitle": "2025 2月",
    "coverImg": "img/monthly/2025/02.jpg",
    "url": "monthly-2025-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "心の奥",
    "artist": "ロクデナシ",
    "desc": "此刻 傷口再次隱隱作痛，在內心深處<br>但眼淚依然純淨無瑕",
    "ytId": "JQjnJ8ZAjzI",
    "date": "2025.02.05",
    "sourceTitle": "2025 2月",
    "coverImg": "img/monthly/2025/02.jpg",
    "url": "monthly-2025-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "Eureka",
    "artist": "星野源",
    "desc": "非常溫暖的一首歌<br>星野源真的是很溫柔的一個人",
    "ytId": "CJS-dnAiiFE",
    "date": "2025.01.30",
    "sourceTitle": "2025 2月",
    "coverImg": "img/monthly/2025/02.jpg",
    "url": "monthly-2025-h1.html#month-02"
  },
  {
    "type": "monthly",
    "name": "Plazma",
    "artist": "米津玄師",
    "desc": "『機動戦士Gundam GQuuuuuuX -Beginning-』主題歌<br>剛過新年就有米津新歌好聽<br>飛向宇宙的彼方望著<br>貫穿眼前的那道電漿",
    "ytId": "fp3F6TqBsAU",
    "date": "2025.01.21",
    "sourceTitle": "2025 1月",
    "coverImg": "img/monthly/2025/01.jpg",
    "url": "monthly-2025-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "言の刃",
    "artist": "ロクデナシ",
    "desc": "感情的，短絡的，衝動的，嘲笑的",
    "ytId": "5cZ4EUhei2g",
    "date": "2025.01.08",
    "sourceTitle": "2025 1月",
    "coverImg": "img/monthly/2025/01.jpg",
    "url": "monthly-2025-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "DiNA",
    "artist": "優里",
    "desc": "與你一同生活的 DiNA<br>優里的新歌<br>歌詞描繪了與重要的人一起生活的美好和珍貴<br>無論是家人、朋友還是戀人<br>這首歌都表達了對他們的感激和愛意",
    "ytId": "hmWWyfWIvyE",
    "date": "2025.01.03",
    "sourceTitle": "2025 1月",
    "coverImg": "img/monthly/2025/01.jpg",
    "url": "monthly-2025-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "夜凪",
    "artist": "indigo la Endfeat.にしな",
    "desc": "情歌王子川谷繪音攜手にしな<br>敘述男女間，有些距離的感情。<br>只想和你一起前行在高速公路上<br>我明白一切，但不想知道真相",
    "ytId": "vJR2K4o52jQ",
    "date": "2025.01.07",
    "sourceTitle": "2025 1月",
    "coverImg": "img/monthly/2025/01.jpg",
    "url": "monthly-2025-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "百花繚乱",
    "artist": "幾田りら",
    "desc": "為藥師少女做的主題曲<br>百花繚亂的歌詞描繪了在充滿挑戰和困難的世界中<br>仍然能夠綻放出美麗和希望的情景<br>就像是百花盛開一般。",
    "ytId": "qvk4Rl7r2GY",
    "date": "2025.01.09",
    "sourceTitle": "2025 1月",
    "coverImg": "img/monthly/2025/01.jpg",
    "url": "monthly-2025-h1.html#month-01"
  },
  {
    "type": "monthly",
    "name": "レイン",
    "artist": "シド",
    "desc": "偶然聽到的老歌<br>沒有很熟悉的歌手<br>卻意外的好聽<br>歌詞描繪了在雨中尋找希望和勇氣的情景<br>就像是在黑暗中尋找光明一樣",
    "ytId": "GB3DN7B4mx4",
    "date": "2023.03.21",
    "sourceTitle": "2025 1月",
    "coverImg": "img/monthly/2025/01.jpg",
    "url": "monthly-2025-h1.html#month-01"
  },
  {
    "type": "theme",
    "name": "夜に駆ける",
    "artist": "YOASOBI",
    "desc": "騒がしい日々に笑えない君に 思い付く限り眩しい明日を<br><span class=\"zh-translate\">在喧囂日子裡已無法露出笑容的你 我會把所能想像到的、最耀眼的明日帶給你</span><br>明けない夜に落ちてゆく前に 僕の手を掴んでほら<br><span class=\"zh-translate\">在墜入那個不會天亮的夜晚前 來吧 緊緊地抓住我的手吧</span><br>忘れてしまいたくて閉じ込めた日々も 抱きしめた温もりで溶かすから<br><span class=\"zh-translate\">那些因為想要遺忘，而封閉自我的日子 我會用擁抱的溫度，將它們慢慢融化</span><br>怖くないよいつか日が昇るまで 二人でいよう<br><span class=\"zh-translate\">不用害怕，在太陽再次升起之前 就讓我們兩個人一起度過吧</span>",
    "ytId": "x8VYWazR5mE",
    "date": "#YOASOBI SELECTION",
    "sourceTitle": "YOASOBI - 日本最強雙人組合再度來台演出！",
    "coverImg": "img/theme/YOASOBI.jpg",
    "url": "playlist.html#theme-12"
  },
  {
    "type": "theme",
    "name": "たぶん",
    "artist": "YOASOBI",
    "desc": "僕らは何回だってきっと そう何年だってきっと<br><span class=\"zh-translate\">我們無論多少次，一定都會 是啊，不論經過多少年，也一定會</span><br>さよならと共に終わるだけなんだ 仕方がないよきっと<br><span class=\"zh-translate\">最終只能伴隨著「再見」而結束 一定也是沒有辦法的事吧</span><br>「おかえり」 思わず零れた言葉は 違うな<br><span class=\"zh-translate\">「歡迎回來。」 不經意脫口而出的這句話 不對啊</span>",
    "ytId": "8iuLXODzL04",
    "date": "#YOASOBI SELECTION",
    "sourceTitle": "YOASOBI - 日本最強雙人組合再度來台演出！",
    "coverImg": "img/theme/YOASOBI.jpg",
    "url": "playlist.html#theme-12"
  },
  {
    "type": "theme",
    "name": "舞台に立って",
    "artist": "YOASOBI",
    "desc": "さあ 待ちに待った舞台に立って 高鳴る鼓動 挑戦の合図<br><span class=\"zh-translate\">來吧 站上那個期待已久的舞台 高昂的心跳，是挑戰開始的信號</span><br>何度も何度も イメージしてきた どんな自分も超えてみせる<br><span class=\"zh-translate\">一次又一次 早已在腦海裡想像過無數次 我要超越那個曾經的自己</span><br>かさぶたばっかの毎日も 今に繋がっていると思えた<br><span class=\"zh-translate\">那些滿是傷痕與結痂的日子 卻也都與此刻緊緊相連</span><br>そうだ夢に見ていた景色の 目の前に立っているんだ<br><span class=\"zh-translate\">沒錯，曾經只能在夢裡看見的景色 如今，我正站在它的面前</span>",
    "ytId": "GWDzKel_vuQ",
    "date": "#YOASOBI SELECTION",
    "sourceTitle": "YOASOBI - 日本最強雙人組合再度來台演出！",
    "coverImg": "img/theme/YOASOBI.jpg",
    "url": "playlist.html#theme-12"
  },
  {
    "type": "theme",
    "name": "ハルジオン",
    "artist": "YOASOBI",
    "desc": "あなたの言葉に頷き信じた私を 一人置き去りに時間は過ぎる<br><span class=\"zh-translate\">曾經點頭相信著你的話的我 被獨自留在原地，而時間仍不停流逝</span><br>見えていたはずの 未来も指の隙間をすり抜けた<br><span class=\"zh-translate\">本來應該看得見的 未來也從指縫之間悄悄溜走</span><br>戻れない日々の欠片と あなたの気配を 今でも探してしまうよ<br><span class=\"zh-translate\">那些再也回不去的日子碎片 以及你的氣息 直到現在，我仍然忍不住尋找著</span><br>まだあの日の二人に手を伸ばしてる<br><span class=\"zh-translate\">我仍然伸出手，試圖觸碰那一天的我們</span>",
    "ytId": "kzdJkT4kp-A",
    "date": "#YOASOBI SELECTION",
    "sourceTitle": "YOASOBI - 日本最強雙人組合再度來台演出！",
    "coverImg": "img/theme/YOASOBI.jpg",
    "url": "playlist.html#theme-12"
  },
  {
    "type": "theme",
    "name": "群青",
    "artist": "YOASOBI",
    "desc": "感じたままに描く 自分で選んだその色で<br><span class=\"zh-translate\">按照自己的感受去描繪 用自己親自選擇的色彩</span><br>眠い空気纏う朝に 訪れた青い世界<br><span class=\"zh-translate\">在瀰漫著慵懶氣息的清晨 迎來了一片蔚藍的世界</span><br>好きなものを好きだと言う 怖くて仕方ないけど<br><span class=\"zh-translate\">對喜歡的東西就說喜歡 雖然對此感到無比害怕</span><br>本当の自分 出会えた気がしたんだ<br><span class=\"zh-translate\">但好像能夠跟真正的自己 就此相遇的感覺</span>",
    "ytId": "Y4nEEZwckuU",
    "date": "#YOASOBI SELECTION",
    "sourceTitle": "YOASOBI - 日本最強雙人組合再度來台演出！",
    "coverImg": "img/theme/YOASOBI.jpg",
    "url": "playlist.html#theme-12"
  },
  {
    "type": "theme",
    "name": "アンコール",
    "artist": "YOASOBI",
    "desc": "ありふれたあの日々をただ思い返す 終わりが来ることを待つ世界で<br><span class=\"zh-translate\">只是回想著那些平凡的日子 在這個等待終結到來的世界裡</span><br>辛い過去も嫌な記憶も 忘れられないメロディーも<br><span class=\"zh-translate\">無論是痛苦的過去，還是討厭的回憶 以及那些無法忘記的旋律</span><br>今日でさよなら<br><span class=\"zh-translate\">今天，就向它們道別</span>",
    "ytId": "vcGbefQBvJ4",
    "date": "#YOASOBI SELECTION",
    "sourceTitle": "YOASOBI - 日本最強雙人組合再度來台演出！",
    "coverImg": "img/theme/YOASOBI.jpg",
    "url": "playlist.html#theme-12"
  },
  {
    "type": "theme",
    "name": "弾きこもり",
    "artist": "AKASAKI",
    "desc": "真面目ぶった音楽で踊る少年がいた<br><span class=\"zh-translate\">有個少年，隨著故作認真的音樂起舞</span><br>それは美しくアマチュアな笑顔<br><span class=\"zh-translate\">那是美麗而青澀的笑容</span><br>真面目ぶった音楽に嫌気が差してんだ<br><span class=\"zh-translate\">對那一本正經的音樂我早已感到厭倦了</span><br>暗い 苦い 今何曜日？ 味が染みた毎日だわ<br><span class=\"zh-translate\">陰沉、苦澀……今天究竟是星期幾？對於日常已感到了麻木</span>",
    "ytId": "n92HOHD5deA",
    "date": "#AKASAKI SELECTION",
    "sourceTitle": "AKASAKI - 爆紅 TikTok 創作奇才來台開唱！",
    "coverImg": "img/theme/AKASAKI.jpg",
    "url": "playlist.html#theme-11"
  },
  {
    "type": "theme",
    "name": "Bunny Girl",
    "artist": "AKASAKI",
    "desc": "夜の始まりさ Bunny Girl 誘惑される鼓動に<br><span class=\"zh-translate\">夜晚開始了，Bunny Girl 面對那令人心動的誘惑</span><br>弾け飛ぶ葛藤に愛を乾杯 伝えられなくても<br><span class=\"zh-translate\">為那爆發而出的掙扎，乾杯吧 即使無法傳達心意</span><br>恋の始まりさ Bunny Girl 誰かを穿って 澄んだ君の目を 孕んで<br><span class=\"zh-translate\">這就是戀愛的開始啊，Bunny Girl 深深刺穿某個人的心 懷抱著你那雙清澈的眼眸</span>",
    "ytId": "WwI7hPXZC-Y",
    "date": "#AKASAKI SELECTION",
    "sourceTitle": "AKASAKI - 爆紅 TikTok 創作奇才來台開唱！",
    "coverImg": "img/theme/AKASAKI.jpg",
    "url": "playlist.html#theme-11"
  },
  {
    "type": "theme",
    "name": "夏実",
    "artist": "AKASAKI",
    "desc": "收錄於首張專輯《last YOUNG》的代表作品，展現濃烈夏日敘事氛圍與獨特歌聲。",
    "ytId": "-xtsHwsvDyY",
    "date": "#AKASAKI SELECTION",
    "sourceTitle": "AKASAKI - 爆紅 TikTok 創作奇才來台開唱！",
    "coverImg": "img/theme/AKASAKI.jpg",
    "url": "playlist.html#theme-11"
  },
  {
    "type": "theme",
    "name": "TOGE",
    "artist": "AKASAKI",
    "desc": "素敵なひと時を頂戴と願う私にくれるのは<br><span class=\"zh-translate\">我只是渴望得到一段美好的時光 可你給我的</span><br>いつも痛い青紫のベールとため息ばかり<br><span class=\"zh-translate\">卻總是疼痛、青紫色的面紗與一聲聲嘆息</span><br>さよなら これ以上はさ 抱えきれないけど 棘になって離れないから<br><span class=\"zh-translate\">再見了 我已經無法再承受更多了 可那些化作了荊棘，始終無法從心裡拔除</span>",
    "ytId": "Z7ICL1ZREnU",
    "date": "#AKASAKI SELECTION",
    "sourceTitle": "AKASAKI - 爆紅 TikTok 創作奇才來台開唱！",
    "coverImg": "img/theme/AKASAKI.jpg",
    "url": "playlist.html#theme-11"
  },
  {
    "type": "theme",
    "name": "徘徊",
    "artist": "AKASAKI",
    "desc": "夜を徘徊 君だけが咲き誇る 目まぐるしくときめく ワンダーランド<br><span class=\"zh-translate\">徘徊於夜裡唯有你盛放得如此耀眼 在令人目眩神迷、心動不已的夢幻世界</span><br>君と徘徊 意味もなく 手を掴み 目まぐるしくときめき 笑うの<br><span class=\"zh-translate\">與你一同徘徊，毫無理由地牽起你的手 在怦然心動中，相視而笑</span><br>ねぇ いっそのことキスをして この蠢く夜さえ 終わらせて<br><span class=\"zh-translate\">吶，不如乾脆吻我吧 連同這躁動不安的夜晚，一起畫下句點</span>",
    "ytId": "lcsOdkPICuQ",
    "date": "#AKASAKI SELECTION",
    "sourceTitle": "AKASAKI - 爆紅 TikTok 創作奇才來台開唱！",
    "coverImg": "img/theme/AKASAKI.jpg",
    "url": "playlist.html#theme-11"
  },
  {
    "type": "theme",
    "name": "恋音と雨空",
    "artist": "AAA (Full Covered by 春茶)",
    "desc": "「好きだよ」と伝えればいいのに<br><span class=\"zh-translate\">明明只要說出一句「我喜歡你」就好了</span><br>願う先、怖くていえず<br><span class=\"zh-translate\">卻害怕那之後的結果，而始終說不出口</span><br>「好きじゃない?」「好きだよ?」が<br><span class=\"zh-translate\">「你不喜歡我嗎？」「我喜歡你喔？」</span><br>揺れる恋と雨空<br><span class=\"zh-translate\">就像陰晴不定的戀情</span><br>君との時間が一秒でも長くなるなら<br><span class=\"zh-translate\">如果能和你多相處哪怕一秒鐘</span><br>ずっとじゃなくていい<br><span class=\"zh-translate\">就算不是永遠也沒關係</span><br>雨が止むまでこのままいさせて。。。<br><span class=\"zh-translate\">就讓我這樣待在你身邊，直到雨停吧……</span>",
    "ytId": "apOelWh2vJU",
    "date": "#HARUTYA SELECTION",
    "sourceTitle": "春茶 - 從翻唱開始的歌手夢",
    "coverImg": "img/theme/春茶cover.png",
    "url": "playlist.html#theme-10"
  },
  {
    "type": "theme",
    "name": "トドカナイカラ",
    "artist": "平井堅 (Full Covered by 春茶)",
    "desc": "毎日君を抱きしめても<br><span class=\"zh-translate\">即使每天都將你擁入懷中</span><br>どんなに強く抱きしめても<br><span class=\"zh-translate\">無論抱得多麼緊</span><br>0.1㎜の不安が挟まったまま<br><span class=\"zh-translate\">心裡仍夾著那僅僅 0.1 毫米的不安</span><br>毎日君に恋するため毎日君を抱きしめよう<br><span class=\"zh-translate\">為了每天都能重新愛上你，我想每天都擁抱著你</span><br>忘れるから移ろうから届かないから<br><span class=\"zh-translate\">因為人會遺忘、會改變，也總有無法傳達的心意</span><br>大好きと笑って欲しい<br><span class=\"zh-translate\">所以，希望你能笑著對我說一句：「我最喜歡你。」</span>",
    "ytId": "3WUUFplHrVk",
    "date": "#HARUTYA SELECTION",
    "sourceTitle": "春茶 - 從翻唱開始的歌手夢",
    "coverImg": "img/theme/春茶cover.png",
    "url": "playlist.html#theme-10"
  },
  {
    "type": "theme",
    "name": "フラレガイガール",
    "artist": "さユり (Full Covered by 春茶)",
    "desc": "わたしをフッてんじゃないよバカ<br><span class=\"zh-translate\">你這個笨蛋，不准甩掉我啊！</span><br>フッていいわけがないでしょ<br><span class=\"zh-translate\">你怎麼可能有資格甩掉我呢？</span><br>たまに倦怠期予防のサプライズも忘れないでと<br><span class=\"zh-translate\">偶爾也別忘了準備一些防止感情倦怠的小驚喜啊</span><br><br>たしかに言ってはいたけれど<br><span class=\"zh-translate\">雖然我確實是這麼說過</span><br>フッていいわけがないでしょ<br><span class=\"zh-translate\">但也不是叫你跟我分手啊！</span><br>あなたの分際でなにをバカなこと<br><span class=\"zh-translate\">憑你這傢伙，到底在說什麼啊</span><br>言い出してさ<br><span class=\"zh-translate\">居然還真的說出口了</span><br><br>もういいから<br><span class=\"zh-translate\">好了啦</span><br>そろそろ種明かししにきてよ<br><span class=\"zh-translate\">差不多該出來揭曉真相了吧</span>",
    "ytId": "DT3XQ-FNUdE",
    "date": "#HARUTYA SELECTION",
    "sourceTitle": "春茶 - 從翻唱開始的歌手夢",
    "coverImg": "img/theme/春茶cover.png",
    "url": "playlist.html#theme-10"
  },
  {
    "type": "theme",
    "name": "Lemon",
    "artist": "米津玄師 (Full Covered by コバソロ & 春茶)",
    "desc": "あの日の悲しみさえ<br><span class=\"zh-translate\">就連那一天的悲傷</span><br>あの日の苦しみさえ<br><span class=\"zh-translate\">就連那一天的痛苦</span><br>そのすべてを愛してた<br><span class=\"zh-translate\">我都曾深深地珍惜著</span><br>あなたとともに<br><span class=\"zh-translate\">因為那一切，都有你陪伴著</span><br>胸に残り離れない<br><span class=\"zh-translate\">始終留在心裡，無法散去的</span><br>苦いレモンの匂い<br><span class=\"zh-translate\">是那苦澀的檸檬香氣</span><br>雨が降り止むまでは帰れない<br><span class=\"zh-translate\">在雨停之前，我還回不去</span><br>今でもあなたはわたしの光<br><span class=\"zh-translate\">直到現在，你依然是我的光</span>",
    "ytId": "clU8c2fpk2s",
    "date": "#HARUTYA SELECTION",
    "sourceTitle": "春茶 - 從翻唱開始的歌手夢",
    "coverImg": "img/theme/春茶cover.png",
    "url": "playlist.html#theme-10"
  },
  {
    "type": "theme",
    "name": "灰色と青",
    "artist": "菅田将暉/米津玄師 (Full Covered by コバソロ & 春茶)",
    "desc": "どれだけ背丈が変わろうとも<br><span class=\"zh-translate\">無論我們長高了多少、成長了多少</span><br>変わらない何かがありますように<br><span class=\"zh-translate\">願仍有一些事物，永遠不會改變</span><br>くだらない面影に励まされ<br><span class=\"zh-translate\">被那些看似微不足道的往日身影鼓舞著</span><br>今も歌う今も歌う今も歌う<br><span class=\"zh-translate\">直到現在，我依然歌唱著、依然歌唱著、依然歌唱著</span>",
    "ytId": "9nCkUgTO5x4",
    "date": "#HARUTYA SELECTION",
    "sourceTitle": "春茶 - 從翻唱開始的歌手夢",
    "coverImg": "img/theme/春茶cover.png",
    "url": "playlist.html#theme-10"
  },
  {
    "type": "theme",
    "name": "カタオモイ",
    "artist": "Aimer",
    "desc": "Darling 夢が叶ったの お似合いの言葉が見つからないよ<br><span class=\"zh-translate\">親愛的，我的願望實現了，我找不到任何足以形容此刻的話語。</span><br>Darling 夢が叶ったの 愛が溢れていく<br><span class=\"zh-translate\">親愛的，我的願望實現了，愛正不斷滿溢而出。</span>",
    "ytId": "kxs9Su_mbpU",
    "date": "#AIMER SELECTION",
    "sourceTitle": "歌單推薦 - Aimer",
    "coverImg": "img/theme/Aimer.jpg",
    "url": "playlist.html#theme-09"
  },
  {
    "type": "theme",
    "name": "Ref:rain",
    "artist": "Aimer",
    "desc": "What a good thing we lose? What a bad thing we knew<br><span class=\"zh-translate\">我們所失去的，究竟是多麼珍貴？我們所明白的，又是多麼難過？</span><br>そんなフレーズに濡れてく 雨の中<br><span class=\"zh-translate\">在雨中，被那樣的話語一點一滴浸濕。</span>",
    "ytId": "mvkbCZfwWzA",
    "date": "#AIMER SELECTION",
    "sourceTitle": "歌單推薦 - Aimer",
    "coverImg": "img/theme/Aimer.jpg",
    "url": "playlist.html#theme-09"
  },
  {
    "type": "theme",
    "name": "Torches",
    "artist": "Aimer",
    "desc": "You're not alone 今 灯火を抱け その闇にむけ<br><span class=\"zh-translate\">你並不孤單，此刻擁抱手中的火光，朝著那片黑暗前進吧！</span><br>Listen to me Cleave your way again<br><span class=\"zh-translate\">聽我說，再次開闢屬於你的道路。</span>",
    "ytId": "DP89-sZL1YM",
    "date": "#AIMER SELECTION",
    "sourceTitle": "歌單推薦 - Aimer",
    "coverImg": "img/theme/Aimer.jpg",
    "url": "playlist.html#theme-09"
  },
  {
    "type": "theme",
    "name": "Polaris",
    "artist": "Aimer",
    "desc": "「僕は一人だ...」そんなこと もう言わせない<br><span class=\"zh-translate\">「我是一個人……」這種話，我再也不會讓你說了。</span><br>いつだって 途惑って 帰ることもできなくなって<br><span class=\"zh-translate\">無論何時都在迷惘著，甚至連回去的路都找不到了。</span>",
    "ytId": "K1kjy1XLx7I",
    "date": "#AIMER SELECTION",
    "sourceTitle": "歌單推薦 - Aimer",
    "coverImg": "img/theme/Aimer.jpg",
    "url": "playlist.html#theme-09"
  },
  {
    "type": "theme",
    "name": "コイワズライ",
    "artist": "Aimer",
    "desc": "ありふれた会話や仕草を 少しも忘れたくはないよ<br><span class=\"zh-translate\">那些再平凡不過的對話與小動作，我一點也不想忘記。</span><br>ゆらり きらり 白雪のように 溶けてしまわないように<br><span class=\"zh-translate\">輕輕搖曳、閃閃發亮，如同白雪一般，願它不要就此融化消失。</span>",
    "ytId": "4LaNC7jB6gY",
    "date": "#AIMER SELECTION",
    "sourceTitle": "歌單推薦 - Aimer",
    "coverImg": "img/theme/Aimer.jpg",
    "url": "playlist.html#theme-09"
  },
  {
    "type": "theme",
    "name": "僕らまた",
    "artist": "SG",
    "desc": "僕らまたそれぞれの道を歩み始めたのさ<br><span class=\"zh-translate\">我們終將各自踏上不同的人生道路開始向前走</span><br>交差点でまた会えたら その時は長い話を語り明かしたいね<br><span class=\"zh-translate\">若能在交會的路口再次相遇，到那時我們就徹夜聊個不停吧</span>",
    "ytId": "hSdcy2_vtaQ",
    "date": "#GRADUATION SELECTION",
    "sourceTitle": "畢業季 - 畢業快樂!",
    "coverImg": "img/theme/畢業.jpg",
    "url": "playlist.html#theme-08"
  },
  {
    "type": "theme",
    "name": "サヨナラの合図",
    "artist": "みなとん",
    "desc": "講述對畢業的感受，既是期待亦有不捨<br><span class=\"zh-translate\">懷念現在的同時，也勇敢邁向人生的下個階段。</span>",
    "ytId": "YUKhmzGPcaM",
    "date": "#GRADUATION SELECTION",
    "sourceTitle": "畢業季 - 畢業快樂!",
    "coverImg": "img/theme/畢業.jpg",
    "url": "playlist.html#theme-08"
  },
  {
    "type": "theme",
    "name": "17さいのうた。",
    "artist": "ユイカ",
    "desc": "拝啓、未来の私へ。<br><span class=\"zh-translate\">致敬，寫給未來的我。</span><br>今そこで どんな大人になって生きていますか。<br><span class=\"zh-translate\">此刻的你，在那裡成為了怎樣的大人、又是如何活著呢。</span>",
    "ytId": "TLvMXOEXi_k",
    "date": "#GRADUATION SELECTION",
    "sourceTitle": "畢業季 - 畢業快樂!",
    "coverImg": "img/theme/畢業.jpg",
    "url": "playlist.html#theme-08"
  },
  {
    "type": "theme",
    "name": "桜晴",
    "artist": "優里 × tuki.",
    "desc": "今はさよなら またねでいいかな<br><span class=\"zh-translate\">現在說再見，用「下次見」來代替，好嗎？</span><br>どんなに遠くなっても忘れたくない<br><span class=\"zh-translate\">無論彼此變得多麼遙遠，我都不想忘記——</span>",
    "ytId": "Lp6OiPCDYYw",
    "date": "#GRADUATION SELECTION",
    "sourceTitle": "畢業季 - 畢業快樂!",
    "coverImg": "img/theme/畢業.jpg",
    "url": "playlist.html#theme-08"
  },
  {
    "type": "theme",
    "name": "手紙 ~拝啓 十五の君へ~",
    "artist": "アンジェラ・アキ",
    "desc": "ひとつしかないこの胸が何度もばらばらに割れて<br><span class=\"zh-translate\">獨一無二的這個心，不論經歷多少波折</span><br>苦しい中で今を生きている<br><span class=\"zh-translate\">在痛苦之中，努力活著、努力活在當下</span>",
    "ytId": "erGCAu_hFqM",
    "date": "#GRADUATION SELECTION",
    "sourceTitle": "畢業季 - 畢業快樂!",
    "coverImg": "img/theme/畢業.jpg",
    "url": "playlist.html#theme-08"
  },
  {
    "type": "theme",
    "name": "おくすり",
    "artist": "ユイカ",
    "desc": "私だけって約束して。<br><span class=\"zh-translate\">答應我，你只有我一個人。</span><br>私は貴方のおくすり 離れられないわ。<br><span class=\"zh-translate\">我是屬於你的藥，你再也無法離開我。</span>",
    "ytId": "-qSqMSsJ4AE",
    "date": "#YUIKA SELECTION",
    "sourceTitle": "青澀系少女歌手- ユイカ",
    "coverImg": "img/theme/yuika.jpg",
    "url": "playlist.html#theme-07"
  },
  {
    "type": "theme",
    "name": "17さいのうた。",
    "artist": "ユイカ",
    "desc": "拝啓、未来の私へ。<br><span class=\"zh-translate\">致敬，寫給未來的我。</span><br>今そこで どんな大人になって生きていますか。<br><span class=\"zh-translate\">此刻的你，在那裡成為了怎樣的大人、又是如何活著呢。</span>",
    "ytId": "TLvMXOEXi_k",
    "date": "#YUIKA SELECTION",
    "sourceTitle": "青澀系少女歌手- ユイカ",
    "coverImg": "img/theme/yuika.jpg",
    "url": "playlist.html#theme-07"
  },
  {
    "type": "theme",
    "name": "すないぱー。",
    "artist": "ユイカ",
    "desc": "きゅん きゅん ぎゅん ぎゅん 急上昇！<br><span class=\"zh-translate\">心動不已、怦然加速、情感急速上升！</span><br>この思いで貴方を撃ち抜いちゃえ！<br><span class=\"zh-translate\">就用這份心意，將你一擊命中吧！</span>",
    "ytId": "nvQN56D8RYo",
    "date": "#YUIKA SELECTION",
    "sourceTitle": "青澀系少女歌手- ユイカ",
    "coverImg": "img/theme/yuika.jpg",
    "url": "playlist.html#theme-07"
  },
  {
    "type": "theme",
    "name": "そばにいて。",
    "artist": "ユイカ",
    "desc": "2人一緒に笑っちゃうよ<br><span class=\"zh-translate\">我們兩個總會一起笑出來呢</span><br>君がそばにいて<br><span class=\"zh-translate\">只要你陪在我身邊</span>",
    "ytId": "AG1o7NN2Dwo",
    "date": "#YUIKA SELECTION",
    "sourceTitle": "青澀系少女歌手- ユイカ",
    "coverImg": "img/theme/yuika.jpg",
    "url": "playlist.html#theme-07"
  },
  {
    "type": "theme",
    "name": "私が選んだもの",
    "artist": "ユイカ",
    "desc": "私が選んだもので生きている<br><span class=\"zh-translate\">我正靠著自己所選擇的事物活著</span><br>貴方が握りしめているものはなんだ？<br><span class=\"zh-translate\">而你緊握在手中的，又是什麼呢？</span>",
    "ytId": "d8coIl7ARZc",
    "date": "#YUIKA SELECTION",
    "sourceTitle": "青澀系少女歌手- ユイカ",
    "coverImg": "img/theme/yuika.jpg",
    "url": "playlist.html#theme-07"
  },
  {
    "type": "theme",
    "name": "お気に召すまま",
    "artist": "Eve",
    "desc": "僕ら今　さあさあ輪になって<br><span class=\"zh-translate\">我們現在，來吧來吧圍成一圈</span><br>回り始める<br><span class=\"zh-translate\">開始轉動起來</span>",
    "ytId": "nROvY9uiYYk",
    "date": "#EVE SELECTION",
    "sourceTitle": "日本邪氣少年 - Eve",
    "coverImg": "img/theme/Eve.jpg",
    "url": "playlist.html#theme-01"
  },
  {
    "type": "theme",
    "name": "擬劇論",
    "artist": "Eve",
    "desc": "ずっと僕は 何者にもなれないで<br><span class=\"zh-translate\">我一直都 成不了任何人</span><br>ドラマチックな展開をどっか期待してんだろう<br><span class=\"zh-translate\">其實你也在某處期待著戲劇性的發展吧</span>",
    "ytId": "jJzw1h5CR-I",
    "date": "#EVE SELECTION",
    "sourceTitle": "日本邪氣少年 - Eve",
    "coverImg": "img/theme/Eve.jpg",
    "url": "playlist.html#theme-01"
  },
  {
    "type": "theme",
    "name": "Last Dance",
    "artist": "Eve",
    "desc": "あなたは言った 消耗品さ<br><span class=\"zh-translate\">你曾說過，我只是消耗品而已</span><br>だけど私は　まだ考えてるわ<br><span class=\"zh-translate\">但我，仍然在思考著</span>",
    "ytId": "CLdeykXCZX4",
    "date": "#EVE SELECTION",
    "sourceTitle": "日本邪氣少年 - Eve",
    "coverImg": "img/theme/Eve.jpg",
    "url": "playlist.html#theme-01"
  },
  {
    "type": "theme",
    "name": "宵の明星",
    "artist": "Eve",
    "desc": "曖昧なままでいたくて<br><span class=\"zh-translate\">想就這樣保持著模糊不清</span><br>最大公約数の先へ<br><span class=\"zh-translate\">朝著那「最大公約數」之外的地方前進</span>",
    "ytId": "pC0ORuJiSw0",
    "date": "#EVE SELECTION",
    "sourceTitle": "日本邪氣少年 - Eve",
    "coverImg": "img/theme/Eve.jpg",
    "url": "playlist.html#theme-01"
  },
  {
    "type": "theme",
    "name": "君に世界",
    "artist": "Eve",
    "desc": "君の世界に色はあったかい<br><span class=\"zh-translate\">在你的世界裡，有顏色存在嗎</span><br>君の世界に僕は在ったかい<br><span class=\"zh-translate\">在你的世界裡，有我的存在嗎</span>",
    "ytId": "B3vsRXOSBqc",
    "date": "#EVE SELECTION",
    "sourceTitle": "日本邪氣少年 - Eve",
    "coverImg": "img/theme/Eve.jpg",
    "url": "playlist.html#theme-01"
  },
  {
    "type": "theme",
    "name": "宿命",
    "artist": "Official髭男dism",
    "desc": "奇跡じゃなくていい<br><span class=\"zh-translate\">不必是奇蹟</span><br>美しくなくていい<br><span class=\"zh-translate\">也不必完美無瑕</span><br>宿命ってやつを燃やして<br><span class=\"zh-translate\">把「宿命」的東西燃燒殆盡</span>",
    "ytId": "-kgOFJG881I",
    "date": "#HIGEDAN SELECTION",
    "sourceTitle": "鬍子男髭男dism即將來台演出！",
    "coverImg": "img/theme/髭男.jpg",
    "url": "playlist.html#theme-02"
  },
  {
    "type": "theme",
    "name": "Pretender",
    "artist": "Official髭男dism",
    "desc": "グッバイ<br><span class=\"zh-translate\">再見了</span><br>君の運命のヒトは僕じゃない<br><span class=\"zh-translate\">你命中註定的那個人，並不是我</span>",
    "ytId": "TQ8WlA2GXbk",
    "date": "#HIGEDAN SELECTION",
    "sourceTitle": "鬍子男髭男dism即將來台演出！",
    "coverImg": "img/theme/髭男.jpg",
    "url": "playlist.html#theme-02"
  },
  {
    "type": "theme",
    "name": "イエスタデイ",
    "artist": "Official髭男dism",
    "desc": "半信半疑で世間体<br><span class=\"zh-translate\">半信半疑地活著</span><br>気にしてばっかのイエスタデイ<br><span class=\"zh-translate\">總是在意他人眼光的昨日</span>",
    "ytId": "DuMqFknYHBs",
    "date": "#HIGEDAN SELECTION",
    "sourceTitle": "鬍子男髭男dism即將來台演出！",
    "coverImg": "img/theme/髭男.jpg",
    "url": "playlist.html#theme-02"
  },
  {
    "type": "theme",
    "name": "Stand By You",
    "artist": "Official髭男dism",
    "desc": "いつもStand By You<br><span class=\"zh-translate\">一直都在妳身邊</span><br>未来がハイになる<br><span class=\"zh-translate\">未來變得高昂、閃耀起來</span><br>Uh Uh 君と歌になる<br><span class=\"zh-translate\">與你一起化作一首歌</span>",
    "ytId": "22mOCjkwQjM",
    "date": "#HIGEDAN SELECTION",
    "sourceTitle": "鬍子男髭男dism即將來台演出！",
    "coverImg": "img/theme/髭男.jpg",
    "url": "playlist.html#theme-02"
  },
  {
    "type": "theme",
    "name": "Subtitle",
    "artist": "Official髭男dism",
    "desc": "正しさよりも優しさが欲しい<br><span class=\"zh-translate\">比起正確，我更想要溫柔</span><br>不特定多数じゃなくてただ1人<br><span class=\"zh-translate\">而是僅僅只有一人</span><br>君であってほしい<br><span class=\"zh-translate\">我只希望——那個人是你</span>",
    "ytId": "hN5MBlGv2Ac",
    "date": "#HIGEDAN SELECTION",
    "sourceTitle": "鬍子男髭男dism即將來台演出！",
    "coverImg": "img/theme/髭男.jpg",
    "url": "playlist.html#theme-02"
  },
  {
    "type": "theme",
    "name": "高嶺の花子さん",
    "artist": "back number",
    "desc": "会いたいんだ<br><span class=\"zh-translate\">我好想見你</span><br>夏の魔物に連れ去られ 僕のもとへ<br><span class=\"zh-translate\">就像被夏日的魔物帶走一樣，來到我身邊吧</span>",
    "ytId": "SII-S-zCg-c",
    "date": "#BACK NUMBER SELECTION",
    "sourceTitle": "大叔系樂團back number即將來台演出！",
    "coverImg": "img/theme/back number.jpg",
    "url": "playlist.html#theme-03"
  },
  {
    "type": "theme",
    "name": "ベルベットの詩",
    "artist": "back number",
    "desc": "あるがままの姿で自分のままで生きさせて<br><span class=\"zh-translate\">讓我以最真實的樣子，作為我自己活下去</span><br>きっと人生は素晴らしい<br><span class=\"zh-translate\">但人生一定是美好的</span>",
    "ytId": "kNH3eExqWFw",
    "date": "#BACK NUMBER SELECTION",
    "sourceTitle": "大叔系樂團back number即將來台演出！",
    "coverImg": "img/theme/back number.jpg",
    "url": "playlist.html#theme-03"
  },
  {
    "type": "theme",
    "name": "ヒロイン",
    "artist": "back number",
    "desc": "雪が綺麗と笑うのは君がいい<br><span class=\"zh-translate\">笑著說「雪好美」的人，我希望是你</span><br>それも君がいい<br><span class=\"zh-translate\">那些全部，也都希望是你</span>",
    "ytId": "VPZK72W4Xxw",
    "date": "#BACK NUMBER SELECTION",
    "sourceTitle": "大叔系樂團back number即將來台演出！",
    "coverImg": "img/theme/back number.jpg",
    "url": "playlist.html#theme-03"
  },
  {
    "type": "theme",
    "name": "ハッピーエンド",
    "artist": "back number",
    "desc": "青いまま枯れてゆく<br><span class=\"zh-translate\">在尚未成熟的狀態下枯萎</span><br>あなたを好きなままで消えてゆく<br><span class=\"zh-translate\">帶著喜歡你的心，就這樣消逝</span>",
    "ytId": "T8y_RsF4TSw",
    "date": "#BACK NUMBER SELECTION",
    "sourceTitle": "大叔系樂團back number即將來台演出！",
    "coverImg": "img/theme/back number.jpg",
    "url": "playlist.html#theme-03"
  },
  {
    "type": "theme",
    "name": "水平線",
    "artist": "back number",
    "desc": "水平線が光る朝に あなたの希望が崩れ落ちて<br><span class=\"zh-translate\">在天際線閃耀的清晨，你的希望分崩離析</span><br>あなたはそれを見るでしょう<br><span class=\"zh-translate\">而你，終究會看見那道光</span>",
    "ytId": "iqEr3P78fz8",
    "date": "#BACK NUMBER SELECTION",
    "sourceTitle": "大叔系樂團back number即將來台演出！",
    "coverImg": "img/theme/back number.jpg",
    "url": "playlist.html#theme-03"
  },
  {
    "type": "theme",
    "name": "BOY",
    "artist": "King Gnu",
    "desc": "息を切らした君は<br><span class=\"zh-translate\">氣喘吁吁的你</span><br>誰より素敵さ<br><span class=\"zh-translate\">比任何人都還要耀眼</span>",
    "ytId": "n0QNaym0jDI",
    "date": "#KING GNU SELECTION",
    "sourceTitle": "邪氣樂團 King gnu 牛羚之王",
    "coverImg": "img/theme/King Gnu.jpg",
    "url": "playlist.html#theme-04"
  },
  {
    "type": "theme",
    "name": "飛行艇",
    "artist": "King Gnu",
    "desc": "この時代に飛び乗って<br><span class=\"zh-translate\">躍上這個時代的浪潮</span><br>命揺らせ 命揺らせ<br><span class=\"zh-translate\">讓生命搖擺吧</span>",
    "ytId": "MSv7NbfbtU8",
    "date": "#KING GNU SELECTION",
    "sourceTitle": "邪氣樂團 King gnu 牛羚之王",
    "coverImg": "img/theme/King Gnu.jpg",
    "url": "playlist.html#theme-04"
  },
  {
    "type": "theme",
    "name": "白日",
    "artist": "King Gnu",
    "desc": "真っ白に全てさよなら<br><span class=\"zh-translate\">向一切純潔地道別</span><br>降りしきる雪よ 全てを包み込んでくれ<br><span class=\"zh-translate\">紛飛不止的雪啊，請將一切都包覆起來</span>",
    "ytId": "ony539T074w",
    "date": "#KING GNU SELECTION",
    "sourceTitle": "邪氣樂團 King gnu 牛羚之王",
    "coverImg": "img/theme/King Gnu.jpg",
    "url": "playlist.html#theme-04"
  },
  {
    "type": "theme",
    "name": "一途",
    "artist": "King Gnu",
    "desc": "生きてる証刻むの<br><span class=\"zh-translate\">刻下自己活著的證明</span><br>矛盾に脳を惑わして<br><span class=\"zh-translate\">讓矛盾擾亂腦海</span>",
    "ytId": "hm1na9R2uYA",
    "date": "#KING GNU SELECTION",
    "sourceTitle": "邪氣樂團 King gnu 牛羚之王",
    "coverImg": "img/theme/King Gnu.jpg",
    "url": "playlist.html#theme-04"
  },
  {
    "type": "theme",
    "name": "Teenager Forever",
    "artist": "King Gnu",
    "desc": "他の誰かになんてなれやしないよ<br><span class=\"zh-translate\">變成其他任何人什麼的，根本不可能做到</span><br>明日を信じてみたいの<br><span class=\"zh-translate\">但我還是想試著去相信明天</span>",
    "ytId": "XPUN-w543bc",
    "date": "#KING GNU SELECTION",
    "sourceTitle": "邪氣樂團 King gnu 牛羚之王",
    "coverImg": "img/theme/King Gnu.jpg",
    "url": "playlist.html#theme-04"
  },
  {
    "type": "theme",
    "name": "青い棘",
    "artist": "神山羊",
    "desc": "こんなくだらない暮らしを許せないの<br><span class=\"zh-translate\">這樣毫無意義的生活是無法被原諒的嗎</span><br>私が古くなって、煙になって、消え交わっている<br><span class=\"zh-translate\">我會逐漸老去，化作煙霧，彼此消散交融</span>",
    "ytId": "PVlVzX6OLns",
    "date": "#RELAXING SELECTION",
    "sourceTitle": "慎入!讓腦袋放空休息",
    "coverImg": "img/theme/relax.jpg",
    "url": "playlist.html#theme-05"
  },
  {
    "type": "theme",
    "name": "LOST CORNER",
    "artist": "米津玄師",
    "desc": "夢も希望も不幸も苦惱全て<br><span class=\"zh-translate\">夢想、希望、不幸和苦惱一切的事情</span><br>まあそれはそれで<br><span class=\"zh-translate\">不過這樣也沒什麼不好吧</span>",
    "ytId": "z2Flmnd3Lkw",
    "date": "#RELAXING SELECTION",
    "sourceTitle": "慎入!讓腦袋放空休息",
    "coverImg": "img/theme/relax.jpg",
    "url": "playlist.html#theme-05"
  },
  {
    "type": "theme",
    "name": "Cuz I",
    "artist": "Siip",
    "desc": "さぁ さぁ 好きなだけ踊り<br><span class=\"zh-translate\">來吧 來吧 盡情地跳舞吧</span><br>疲れてしまいなさい<br><span class=\"zh-translate\">直到精疲力盡為止</span>",
    "ytId": "rgn7JA3zHE0",
    "date": "#RELAXING SELECTION",
    "sourceTitle": "慎入!讓腦袋放空休息",
    "coverImg": "img/theme/relax.jpg",
    "url": "playlist.html#theme-05"
  },
  {
    "type": "theme",
    "name": "LOOP",
    "artist": "SIRUP",
    "desc": "何度でもFalling falling love<br><span class=\"zh-translate\">不管多少次都會再次 Falling falling love</span><br>君との一日を 繰り返し<br><span class=\"zh-translate\">與你共度的一天 不斷重複</span>",
    "ytId": "mHrjM6oVez0",
    "date": "#RELAXING SELECTION",
    "sourceTitle": "慎入!讓腦袋放空休息",
    "coverImg": "img/theme/relax.jpg",
    "url": "playlist.html#theme-05"
  },
  {
    "type": "theme",
    "name": "あなたといたい",
    "artist": "Ayumu Imazu",
    "desc": "行き場のない歌を今届けたいのさ<br><span class=\"zh-translate\">無處可去的這首歌，此刻我想傳達出去</span><br>あなただけに<br><span class=\"zh-translate\">只為了你</span>",
    "ytId": "UfcDAoD7acw",
    "date": "#RELAXING SELECTION",
    "sourceTitle": "慎入!讓腦袋放空休息",
    "coverImg": "img/theme/relax.jpg",
    "url": "playlist.html#theme-05"
  },
  {
    "type": "theme",
    "name": "君の前だと溶けちゃうの",
    "artist": "Leina",
    "desc": "君の前だと溶けちゃうの<br><span class=\"zh-translate\">在你面前，我就會融化</span><br>早く大人にさせてよ<br><span class=\"zh-translate\">快點讓我變成大人吧</span>",
    "ytId": "HuGVpUumJM0",
    "date": "#RELAXING SELECTION",
    "sourceTitle": "慎入!讓腦袋放空休息",
    "coverImg": "img/theme/relax.jpg",
    "url": "playlist.html#theme-05"
  },
  {
    "type": "theme",
    "name": "ベテルギウス",
    "artist": "優里",
    "desc": "僕ら見つけあって 手繰りあって<br><span class=\"zh-translate\">我們找到了彼此，彼此吸引</span><br>遥か遠く終わらない ベテルギウス<br><span class=\"zh-translate\">遙遠沒有終點的參宿四</span>",
    "ytId": "-n790YakYKc",
    "date": "#YUURI SELECTION",
    "sourceTitle": "歌單推薦 - 優里",
    "coverImg": "img/theme/Yuuri.jpg",
    "url": "playlist.html#theme-06"
  },
  {
    "type": "theme",
    "name": "おにごっこ",
    "artist": "優里",
    "desc": "追いかける番になって 初めてわかったよ<br><span class=\"zh-translate\">輪到我去追逐的時候，我才第一次明白</span><br>その背中に触れたくて 走ってた事<br><span class=\"zh-translate\">因為想要觸碰你的背影，我才拼命奔跑著</span>",
    "ytId": "m3VnVRHOMZM",
    "date": "#YUURI SELECTION",
    "sourceTitle": "歌單推薦 - 優里",
    "coverImg": "img/theme/Yuuri.jpg",
    "url": "playlist.html#theme-06"
  },
  {
    "type": "theme",
    "name": "レオ",
    "artist": "優里",
    "desc": "名前呼んでよ 君がつけてくれた名前だから<br><span class=\"zh-translate\">請呼喚這個名字，因為這是你給我取的名字</span><br>傍に居ると決めた大事な人<br><span class=\"zh-translate\">但你是我決定了會待在身旁重要的人</span>",
    "ytId": "uxYLXaXtH9I",
    "date": "#YUURI SELECTION",
    "sourceTitle": "歌單推薦 - 優里",
    "coverImg": "img/theme/Yuuri.jpg",
    "url": "playlist.html#theme-06"
  },
  {
    "type": "theme",
    "name": "メリーゴーランド",
    "artist": "優里",
    "desc": "アイシテルをもう何度 私、口にしたのだろう<br><span class=\"zh-translate\">「我愛你」這句話，我究竟在口中重複了多少回</span><br>寂しさだけがこの胸に残っているのです<br><span class=\"zh-translate\">結果只剩下寂寞，留存在我的心中</span>",
    "ytId": "eWeSqrRk-gs",
    "date": "#YUURI SELECTION",
    "sourceTitle": "歌單推薦 - 優里",
    "coverImg": "img/theme/Yuuri.jpg",
    "url": "playlist.html#theme-06"
  },
  {
    "type": "theme",
    "name": "ビリミリオン",
    "artist": "優里",
    "desc": "僕が⽣きてるこの時間は 50億以上の価値があるでしょう<br><span class=\"zh-translate\">我活著的這段時間，應該有超過五十億的價值吧</span><br>⽣きているだけでまるもうけ<br><span class=\"zh-translate\">光是活著，本身就是最大的收穫</span>",
    "ytId": "vUsikBoa8i0",
    "date": "#YUURI SELECTION",
    "sourceTitle": "歌單推薦 - 優里",
    "coverImg": "img/theme/Yuuri.jpg",
    "url": "playlist.html#theme-06"
  },
  {
    "type": "theme",
    "name": "ピーターパン",
    "artist": "優里",
    "desc": "大人の言う常識なんてものは 丸めて捨てちまえ<br><span class=\"zh-translate\">大人們口中的「常識」這種東西，揉成一團直接扔掉就好</span><br>おとぎ話みたいなハッピーエンドを思い描いて生きていくんだ<br><span class=\"zh-translate\">依然追尋著宛如童話的幸福結局，懷抱著夢想繼續活下去</span>",
    "ytId": "9qfPF4fpiHE",
    "date": "#YUURI SELECTION",
    "sourceTitle": "歌單推薦 - 優里",
    "coverImg": "img/theme/Yuuri.jpg",
    "url": "playlist.html#theme-06"
  }
];
